### ISSUE TITLE
Problem that bios is in exe format

### ISSUE THREAD

**Issue by mojarrah** [xCuri0/ReBarUEFI#103]
**System**
Alienware a51 R4 pc
 - Motherboard: ms-7a87
![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/8c089f67-d1b1-41dd-91c2-6ac317d6a139)

 - BIOS Version: 2.0.7
 - GPU: 3090

Hey. Hope you are doing great. I wanted to follow your steps to activate rebar. but I was surprised that dell bios is .exe and not .bin

How can we fix it?

This is the bios link

https://dl.dell.com/FOLDER08945518M/1/Alienware_Area_51_R4_2.0.7.exe

**Comment by xCuri0** [comment]
On most prebuilts usually the only way to flash is through use of a hardware flasher like CH341A

@Electron-PSO might know more about this

**Comment by mojarrah** [comment]
Could be talk on discord? whats your username

**Comment by Electron-PSO** [comment]
Hello @mojarrah 

You can extract the .rom file from the EXE file by using the /writeromfile switch at the command line

Alienware_Area_51_R4_2.0.7.exe /writeromfile

Once you have the file, you should be able to use the AMI AFUWin64 v3.05.04 with GAN support  to flash it.

As xCuri0 said, make backups first though

AFUWINx64.EXE /O      to save current ROM image to file

**Comment by mojarrah** [comment]
@Electron-PSO Got it, but could we discuss it on Discord now? whats your username? mine uchihamj

**Comment by mojarrah** [comment]
@Electron-PSO here or there, Use what's best for you. The problem is that any version of the bios I can't even open the exe file normally when clicking it in windows 11. Any version of the bios. It gives an error unable to load driver!!! Can you try please to extract it on your side and upload it. That would be l insanely helpful!!!

**Comment by Electron-PSO** [comment]
Hello @mojarrah,

Here is the rom file extracted from the 2.0.7 exe you posted


[alienware_area_51_r4_2.0.7.rom.zip](https://github.com/xCuri0/ReBarUEFI/files/13632962/alienware_area_51_r4_2.0.7.rom.zip)


Did you use the command line when you tried to extract it?  Like this?

<img width="460" alt="Writeromfile" src="https://github.com/xCuri0/ReBarUEFI/assets/134448040/c27b2c02-a5d3-4ebc-a4cf-450c0a5e0fbd">

**Comment by mojarrah** [comment]
Hello @Electron-PSO 

Can confirm the ROM is working. Thanks

Moreover, I have written the same command but didn't work on the machine. It is Windows 11. Maybe it needs to be on Windows 10 to be extracted

Plus, can you please now in the form of steps, tell me exactly what I should do now(anything other than the rebar steps since they are on the site) and if you name any program send its link please

**Comment by Electron-PSO** [comment]
Hello @mojarrah ,

After you have the ReBAR modified file, you'll need something like AMI AFUWin64 v3.05.04 with GAN support to flash it.

See this guide for instructions.  I'm not sure about Win11, but I have managed to get Dell Alienware machines to flash in windows before.

https://winraid.level1techs.com/t/guide-how-to-flash-a-modded-ami-uefi-bios/30627

**Comment by mojarrah** [comment]
@Electron-PSO Downloaded the correct AMI version now

Can you mod the rom file with the uefirebar and upload it, please? since it is different from what other people have shown

**Comment by Electron-PSO** [comment]
Hello @mojarrah ,

It shouldn't be that different.

Search for the DXE section and insert the ReBar ffs at the end of it?

**Comment by mojarrah** [comment]
@Electron-PSO Look what it is giving me

![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/fd68ae15-bcd5-4e98-8f08-e68b3193609b)

**Comment by mojarrah** [comment]
@Electron-PSO But it is giving this error when trying to flash

**Comment by Electron-PSO** [comment]
P.S    I'm at work, so it is difficult for me to respond quickly.

**Comment by mojarrah** [comment]
@Electron-PSO downloaded windows 10. Now. The problem was from windows 11

But when flashing, it gives an error

Rom file size doesn't match the bios file and that true

Rom file 16mb

.exe around 8mb


![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/b3be840e-1f7a-419c-86e9-7cab0197cdd6)

**Comment by Electron-PSO** [comment]
Can you read the BIOS chip with the /O  option?

**Comment by Electron-PSO** [comment]
AFUWINx64.EXE /O to save current ROM image to file

**Comment by mojarrah** [comment]
@Electron-PSO ![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/3d01779a-e033-45c2-a470-af6c8712ce3e)

It is showing this when writing the command

**Comment by Electron-PSO** [comment]
You need to specify the file name you want to make

AFUWINx64.EXE backup.rom /O

**Comment by mojarrah** [comment]
Did and it said it's done. I restarted then used rebar program to to put 32 value. It said it did success. Restarted again but it still shows as disabled in gpuz 

![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/fe913e7c-ea0c-427e-a412-e0e87e845523)

**Comment by mojarrah** [comment]
@Electron-PSO look

![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/d4d7ad6e-cb45-49d1-85f6-0c98926d4651)

**Comment by xCuri0** [comment]
Make sure you have updated vbios on 3090

NVIDIA put out an update for it that's required for resizable bar to work

**Comment by mojarrah** [comment]
@Electron-PSO @xCuri0 

vbios and everything updated
![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/517dc0bd-eb09-4c64-aabf-c11bd83e11c6)

**Comment by mojarrah** [comment]
Literary the only option saying no in gpu z about rebar is: enabled in bios: no

**Comment by mojarrah** [comment]
@xCuri0 what do you think?

**Comment by mojarrah** [comment]
@Electron-PSO I used /O command again to check if the bios really flashed. And put it in uefi tool. And it's still the same. It didn't flash the modded bios

**Comment by Electron-PSO** [comment]
Did you run  ReBarState.exe  to set the BAR size?

**Comment by mojarrah** [comment]
@Electron-PSO Yes

**Comment by mojarrah** [comment]
@Electron-PSO also,

I used /O command again to check if the bios really flashed. And then I did put it in uefi tool. And the result were the bios didn't change. It didn't apply the modded bios. it's still the same. It didn't flash the modded bios

**Comment by mojarrah** [comment]
@Electron-PSO Is there a way to force it 100% to flash?

**Comment by xCuri0** [comment]
Maybe you need to set service jumper or something for it to flash

But best and safest method for flashing prebuilts is using a hardware
flasher like Ch341a

**Comment by mojarrah** [comment]
@xCuri0 Damn, I don't have a hardware flasher currently. Is their another way/software I can try

**Comment by Electron-PSO** [comment]
Would ReBarState be happy if the flash hadn't worked?

**Comment by mojarrah** [comment]
Didn't get what you mean @Electron-PSO

**Comment by Electron-PSO** [comment]
Did you use the /GAN command to flash the BIOS file?

It might not be needed, but worth a try.

AFUWINx64.exe modified.rom /GAN

**Comment by mojarrah** [comment]
Yes

**Comment by Electron-PSO** [comment]
If ReBarState couldn't set the variable it should error?

Try setting it to 1GB bar size

Then reboot

Then check with CPU-Z

**Comment by mojarrah** [comment]
Tried but didn't work also!!

**Comment by Electron-PSO** [comment]
OK

Ignore that last post

I see it does create and is happy with the variable on systems without the BIOS mod

**Comment by Electron-PSO** [comment]
So ReBarState shows it is set to some GB?

**Comment by mojarrah** [comment]
I set it to 10, which is 1gb(as far as I now) and it says successful. But still says disabled after reboot

![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/399ab774-d986-4952-9c64-8fd744907c69)

**Comment by xCuri0** [comment]
> Would ReBarState be happy if the flash hadn't worked?

Yes all it does is write a UEFI variable

**Comment by mojarrah** [comment]
So what to do?

**Comment by Electron-PSO** [comment]
I'm still finding it hard to believe the flash program can erase, program and verify without it actually doing it.

Not sure what to do now.

You could try a different flashing program or you could just do it the physical way.

If I had the board on my desk I would do this:

- Unsolder the chip  
- Put it in a programmer
- Read and save the current file
- Erase the chip
- Program it with the new file
- Resolder it

But that depends on your ability to do the job.

**Comment by mojarrah** [comment]
@Electron-PSO 
Do you recommend another flashing program? What is it? 

Also, is their somehow a bios settings that is activated that didn't allow it to be flashed

Btw, when it flashed it didn't reboot by itself like I would expect it to happen, it just closed the cmd pop up. I rebooted manually

**Comment by Electron-PSO** [comment]
For some Dell machines, I have used a Windows GUI version of the AMI flash tool

**Comment by Electron-PSO** [comment]
I'll have a look for it

**Comment by Electron-PSO** [comment]
Here is the official link to the AMI flash utilities

https://www.ami.com/bios-uefi-utilities/

There are Win GUI versions in the zip folders

x64

**Comment by mojarrah** [comment]
There are multiple links for download 

Drop the link for the exact one I should use

**Comment by mojarrah** [comment]
@Electron-PSO got it now and opened successfully The correct version

Moreover, what settings I should check to make it work 100%

![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/f4607824-bbf4-4488-91ee-58ddeb15b59b)

**Comment by mojarrah** [comment]
@xCuri0 I flashed it successfully now using fpt win32 version as winpad site suggests. The problem now is if I activate the rebar and reboot screen no longer work. The system boot but their is no screen. I have to reset the bios using the battery to get it working. What is the solution?

**Comment by Electron-PSO** [comment]
Apologies for the delay,

I was travveling home and had some sleep.

It should be the Aptio V version

**Comment by Electron-PSO** [comment]
Try a small BAR size first

1GB

**Comment by Electron-PSO** [comment]
Then check in GPU-Z

**Comment by mojarrah** [comment]
What number to put in rebar to equal 1gb? @xCuri0 @Electron-PSO

**Comment by Electron-PSO** [comment]
It is 2^x        so for 1GB  set it to 10

**Comment by mojarrah** [comment]
@Electron-PSO it worked!!!!

Now I can set it to the maximum of what my gpu can handle 

It's a 3090 24gb vram

**Comment by Electron-PSO** [comment]
You'll need 15  as the bar size to give you 32GB.  That will be enough to fit the 24GB VRAM

**Comment by mojarrah** [comment]
What's the best value?

**Comment by Electron-PSO** [comment]
Which Intel FPT did you use?

Have a link to it also?


I'm helping someone with a system and they have flashing issues too

**Comment by mojarrah** [comment]
Will send the link after the pc boot from pc bios reset

Moreover, it isn't working with anything above 1 or 2gb

@xCuri0 

Tried multiple values, all of them led to failure!! What should I do?

**Comment by Electron-PSO** [comment]
Did you apply the patches via UEFI Patch tool ?

https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch

**Comment by Electron-PSO** [comment]
I've just applied the parches to the extracted rom file.

Two patches are applied

These would prevent you from using a 32GB BAR size

# PciBus | Don't downgrade 64-bit BARs to 32-bit (Haswell)
3C1DE39F-D207-408A-AACC-731CFB7F1DD7 10 P:833E067506C70604000000833E077506C70605000000:66906690669066906690669066906690669066906690 

# PciBus | Remove <64GB BAR size limit (Skylake/Kaby Lake/Coffee Lake)
3C1DE39F-D207-408A-AACC-731CFB7F1DD7 10 P:B800000000100000004C3B:B8FFFFFFFFFFFFFF004C3B

**Comment by mojarrah** [comment]
Good, how to make sure the pad isn't corrupted? I couldn't figure it out

**Comment by mojarrah** [comment]
Also, should I remove the .patched extension before flashing or what?

**Comment by mojarrah** [comment]
@Electron-PSO ?

**Comment by mojarrah** [comment]
@xCuri0

**Comment by mojarrah** [comment]
@Electron-PSO I am also thinking to reflash the bios using the x64 version of ftp. What do you think? Is there a difference?

**Comment by Electron-PSO** [comment]
If the 32 bit version worked, keep using it

Steps to take:

- Make ROM file from EXE
- Add ReBarDxe.ffs at end of DXE section
- Apply Patches

you'll get BIOS.ROM then BIOS_ReBAR.ROM  then BIOS_ReBAR_Patched.ROM

I like to keep the .ROM extension and only one   .    in the filename

**Comment by mojarrah** [comment]
Alright, so when the yeti patch give me bios.rom.patched

I remove the .patched extension?

**Comment by mojarrah** [comment]
@Electron-PSO @xCuri0 tried it now. It applied two patches by it self when I written the code. I flashed the bios. Put a value of 13 which is 8gb. When it rebooted. It started beeping and I had to flash the bios again!!!!

**Comment by xCuri0** [comment]
You have to enable 4G decoding and disable csm

**Comment by mojarrah** [comment]
@xCuri0 

Csm is disabled and 4g decoding enabled

Also, I have a skylake processor. And I flashed the bios with win32 version of the tool

And I didn't change anything in patches.txt, I just applied the code as is

![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/4afbcecc-313a-4d6a-8ebe-d2b813f39a71)

**Comment by mojarrah** [comment]
@xCuri0 so what do you think?

**Comment by mojarrah** [comment]
This is what It shows when I use uefipatch with this code:

.\uefipatch .\rebar.bin


![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/2c5f5efa-6dd9-46c3-8cae-c7ce8fc5b05c)

**Comment by mojarrah** [comment]
@xCuri0 @Electron-PSO  adding to the above

Why there are 3 bars showing in gpuz

BAR0
BAR1
BAR2

**Comment by Electron-PSO** [comment]
It is like this on Nvidia cards

BAR1 is the VRAM 
BAR0 are Registers
BAR2 is something else

🤣

**Comment by Electron-PSO** [comment]
So, even with the patches you can't use BAR greater than 2GB?

**Comment by mojarrah** [comment]
Yes, I applied the patches but it still won't boot after using big value. Tried 4, 8, 32 nothing worked

**Comment by mojarrah** [comment]
Also, right now, I tried 11. Which means 2gb and it is also not working

Only 1gb working!!!!

What is going on?!!!

@Electron-PSO @xCuri0

**Comment by mojarrah** [comment]
@xCuri0  @Electron-PSO 

This is the raw working bios

[backup2.zip](https://github.com/xCuri0/ReBarUEFI/files/13661076/backup2.zip)

**Comment by Electron-PSO** [comment]
That file is only 12MB

It should be 16MB for a full chip

**Comment by Electron-PSO** [comment]
Have you got the file you want to flash into the chip?

**Comment by mojarrah** [comment]
This is the file I read from the chip. And it's the raw version

It's 12mb

The one we get from .exe gives error if you remember from the first time we tried

![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/f9110f25-b617-411f-8d7a-de8696f88dab)

**Comment by Electron-PSO** [comment]
The 16MB file from the exe extraction gives an error?

**Comment by mojarrah** [comment]
@Electron-PSO what do you think I should Do?

**Comment by mojarrah** [comment]
@Electron-PSO That what it gives when I try to flash it using fpt 

![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/ad0e3094-be1b-4556-a9a1-1884ce9bbc44)

**Comment by mojarrah** [comment]
@Electron-PSO The 16mb one I mean

**Comment by Electron-PSO** [comment]
Have you flashed the board with the latest BIOS using the normal update tool?

**Comment by Electron-PSO** [comment]
So it looks like the 12MB file you read out is the option to use.

Update to the latest bios version and then read out the file.

Perform the mods

Flash mod file.

Reboot

**Comment by Electron-PSO** [comment]
I think the 16MB file we got from the EXE is 12MB with some padding at the end

**Comment by mojarrah** [comment]
Yes, I did all of this process on the latest bios version already. 

Moreover, I have no problem in downgrading. And I have an older bios version .exe file. But how can extract the 12mb Rom from it?

**Comment by Electron-PSO** [comment]
You could just flash the older version then read out the "Bios" part with FMT.

**Comment by Electron-PSO** [comment]
This Dell stuff   geeez

If x299 boards were not so expensive, I would recommend just replacing the board with an ASUS alternative.

**Comment by mojarrah** [comment]
It doesn't allow me to downgrade to older version when using the .exe

**Comment by mojarrah** [comment]
How to get the 12mb version from the exe?

**Comment by mojarrah** [comment]
@Electron-PSO @xCuri0 

I literally returned to version 1 of the bios which is the oldest version

It booted successfully. Did rebar of value 11 to try. But it did beep like before and the system didn't start!!!!!!!

**Comment by mojarrah** [comment]
What should I do!!!!

**Comment by xCuri0** [comment]
@mojarrah maybe dell has some other bios setting that needs to be enabled for 4g decoding to work fully

and u could try connecting monitor to igpu, sometimes u need to do that when using rebar on skylake and the gpu will output when windows loads

**Comment by mojarrah** [comment]
@xCuri0 I have a dell a51 r4. Someone on Dell forms who has r2 but basically literally like the same bios. He was able to modify the bios and unhide the pci settings menu

How can I do it?

**Comment by xCuri0** [comment]
@mojarrah did you already say you enabled 4g decoding ?

there is a whole page for this, https://github.com/xCuri0/ReBarUEFI/wiki/Enabling-hidden-4G-decoding worked for several dell users

**Comment by mojarrah** [comment]
@xCuri0 Hey

**Comment by mojarrah** [comment]
@xCuri0 Gpu z was showing that above 4g is enabled while it actually was disabled

I unhide the bios menus to enable it

Is there something in these menus I should do before trying?

![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/ba4ba26b-1780-4a17-bcb4-2b3614aef613)

**Comment by mojarrah** [comment]
@xCuri0 

![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/eb4c40ac-7bde-44c9-8be3-e921755d65d3)

**Comment by xCuri0** [comment]
@mojarrah there is nothing to do besides enabling 4g decoding, disabling csm and enabling rebarstate

also it's mentioned in multiple places that gpu-z in inaccurate and that almost no oems enable 4g decode by default idk why you thought it would be

**Comment by mojarrah** [comment]
@xCuri0 I tried value of 15 while above 4g is enabled and it started beeping!!

**Comment by xCuri0** [comment]
@mojarrah there are several things in the common issues wiki page you can try relating to skylake/kabylake systems (lga1151). i know you have x299 but it's probably similar

![image](https://github.com/xCuri0/ReBarUEFI/assets/29529557/d265e690-b658-48e6-9403-e8174de21676)


also some systems beep but eventually display output once windows loads

**Comment by mojarrah** [comment]
@xCuri0 Got it, btw I don't have igpu. Only the 3090. And it's connected using a display port to the screen

**Comment by mojarrah** [comment]
@xCuri0 I waited for it now. Didn't boot. Kept beeping

I tried also hdmi instead of the display port

Still not working

Btw, I have 64gb of rams. So I don't know if that may cause a problem

**Comment by mojarrah** [comment]
@xCuri0 

Just to make sure, 100000% 

After this selection, I insert the pfs of rebar, right?

 ![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/42c1570c-fbad-4a45-be89-c93bfd417190)

**Comment by xCuri0** [comment]
Doing this again won't solve the issue you have, the rebar module clearly
is working fine without any issues


The only thing that might be causing it is not having applied Uefipatch but
iirc you did

**Comment by mojarrah** [comment]
This is what it showes when I apply the patch

Didn't change any single thing in patches.txt

Just typed the command and it did this

So is it correct


Moreover, when I flash the patched version…Should I remove the .patched extension and so it becomes xxx.bin

![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/a63ac463-9e93-4055-a45a-3bcf76209fdf)

**Comment by xCuri0** [comment]
@mojarrah 

> Should I remove the .patched extension and so it becomes xxx.bin

Yes, idk if it's required for FPT tho but using BIOS menus to flash like on my Gigabyte board it is

**Comment by mojarrah** [comment]
Also, is it correct how I applied the patch?

**Comment by xCuri0** [comment]
Yes

**Comment by mojarrah** [comment]
Damnnnn!!!! So what is the problem?!!

I did every single step required

**Comment by xCuri0** [comment]
I don't really know anything more you can try if 4G decoding is really
enabled.

You can read the GitHub wiki pages for this project, one of them tells how
to modify hidden settings using setup_var. Maybe some other setting is
required to be set on Dell but only you could figure it out.


I remember some Dell Ivy Bridge system needed a custom uefipatch made but I
was only able to do it because of how similar to it was to other Ivy Bridge
motherboards

**Comment by mojarrah** [comment]
Alright, is their any other way I could check that 4g is 100% really enabled?

**Comment by xCuri0** [comment]
@mojarrah if it says enabled in the BIOS menu then it is.

Maybe Dell has some additional setting needed to be enabled only you could figure that our

**Comment by mojarrah** [comment]
Btw it gives 3 beeps

Then 3 beeps

Then 3 beeps

And so on

**Comment by mojarrah** [comment]
@xCuri0 the funny thing this that now, even 1gb makes it not boot

**Comment by mojarrah** [comment]
@xCuri0 btw I haven't applied dsdt patching. Is it required?

**Comment by mojarrah** [comment]
@xCuri0 realized something now, when enabling 4g decoding either in unhiding menu in bios or through setup var. Rebar doesn't work at all

Even 1gb doesn't work

Without enabling above 4g. I can do 1gb but nothing above

Why!!!!

**Comment by Electron-PSO** [comment]
I see you have 64GB of RAM

I think 3 beeps is RAM issue?

Do you have 8 sticks of ram?

If so, remove 4 (the correct4)

**Comment by mojarrah** [comment]
I have 4 slots @Electron-PSO

**Comment by mojarrah** [comment]
@Electron-PSO @xCuri0 

Btw, when I searched in uefitool

Both “64 bit resource allocation” and “4g decod” appear when searching for them

And one has 0xF97 value 

And one has 0x403 value

**Comment by Electron-PSO** [comment]
Can you tke out some sticks and try again?

There are some reports of more than 32GB being a problem.

If it is that, then all of this is for nothing until it can be resolved.

**Comment by Electron-PSO** [comment]
I take it you have 16GB DIMMS.

Try just using one stick

With the 3 beeps when it fails to boot, it might be a memory error.

At this point, I'm just throwing ideas about

🤖

**Comment by mojarrah** [comment]
@xCuri0 @Electron-PSO 

I removed 3 of the 4

Nothing changed, still beeps

Moreover, now, I searched using uefi editor in the bios for menus related to the thing

I found another thing related to 4g. It's called above 4g mmio bios assignment

Does it have a role?

**Comment by xCuri0** [comment]
> @xCuri0 @Electron-PSO
> 
> I removed 3 of the 4
> 
> Nothing changed, still beeps
> 
> Moreover, now, I searched using uefi editor in the bios for menus related to the thing
> 
> I found another thing related to 4g. It's called above 4g mmio bios assignment
> 
> Does it have a role?

Yes enable that too

**Comment by xCuri0** [comment]
> Can you tke out some sticks and try again?
> 
> There are some reports of more than 32GB being a problem.
> 
> If it is that, then all of this is for nothing until it can be resolved.

I think X299 shouldn't have any issues like this

**Comment by mojarrah** [comment]
> issues

Yes It doesn't any of these ram issues. I took 3 of the ram sticks. And still beeped. 

I will try your last 3 advices and update you asap

**Comment by mojarrah** [comment]
@xCuri0 

I also found this setting in uefi editor, should I enable it?


![image](https://github.com/xCuri0/ReBarUEFI/assets/111957484/44326378-4305-42c2-ac85-db995aed9944)

**Comment by xCuri0** [comment]
No unless you have some issue with the USB 3 ports

**Comment by xCuri0** [comment]
Also please use setup_var to change hidden settings instead of flashing
because it's way safer no risk of brick.


All this stuff in the wiki page hidden 4g decoding

**Comment by mojarrah** [comment]
@xCuri0 the thing I find very strange is when enabling 4g decoding. Then Even 1gb won't work

**Comment by Electron-PSO** [comment]
Do you get an improvement in performance with the 1GB or 2GB BAR Size?

**Comment by mojarrah** [comment]
Yes. Btw I found something

I had a thought, why is even 1gb not working when enabling 4g decoding

Tried everything, still don't work 

Until, right now, I redid the mod but without the uefi patch and then enabled 4g decoding. Tried a value of 1gb. It works. It doesn't beep now. But when using value of 32. It loads windows but doesn't post to screen

**Comment by mojarrah** [comment]
@xCuri0 @Electron-PSO read above

**Comment by mojarrah** [comment]
@xCuri0 tried everything setup_var and everything else

Like what the heck!!!!

The only time it worked is when I applied 4g decoding and 32 value. Without uefi patch. It turns on and system loads but doesn't post on sceeen(black screen)

If I use the patch with 4g decoding enabled then it will beep

**Comment by xCuri0** [comment]
Try setup_var stuff without uefipatch then

**Comment by mojarrah** [comment]
@xCuri0 should I change anything using setup bar beside the 4g decoding enabled or disabled?

**Comment by xCuri0** [comment]
You already said there was several other things you can change

**Comment by mojarrah** [comment]
Tried now with only 4g using setup var and without uefi patch

It boots but doesn't show anything on the screen

**Comment by mojarrah** [comment]
@xCuri0 enabled now using setup_var

Above 4GB MMIO BIOS assignment,

Above 4g decoding 

64 bit resource something

Still it fully boots but doesn't show anything on screen!!!!!!!!!!

**Comment by mojarrah** [comment]
@Electron-PSO @xCuri0 what should I do?!!

**Comment by mojarrah** [comment]
> @xCuri0  @Electron-PSO 
> 
> 
> 
> This is the raw working bios
> 
> 
> 
> [backup2.zip](https://github.com/xCuri0/ReBarUEFI/files/13661076/backup2.zip)
> 
> 

@xCuri0 This is my bios. Unedited

I tried every single thing. It didn't work!!!!

I am so sad and disparate

**Comment by mojarrah** [comment]
@xCuri0 @Electron-PSO anyone?

**Comment by mojarrah** [comment]
@Electron-PSO I got in new asus prime a x299 motherboard

**Comment by mojarrah** [comment]
@Electron-PSO but i am having a problem in booting. It would be amazing if you can help me a bit

**Comment by mojarrah** [comment]
@Electron-PSO not booting problem from rebar. But booting problem after swapping motherboards

**Comment by Electron-PSO** [comment]
Hello @mojarrah   is she posting at all?

**Comment by mojarrah** [comment]
@Electron-PSO I got it working. But I have a very strange problem

In hwinfo or msi afterburner statistics, cpu is working perfectly except it shows the power consumption of it is 2w max. It goes between 1 and 2!!!!

**Comment by Electron-PSO** [comment]
Windows 10 or 11 ?

Are there any missing devices in Device Manager?

Maybe you need a Chipset.inf for your board?

**Comment by mojarrah** [comment]
@Electron-PSO windows 11

And you are right. Thanks got it fixed

Btw, my alienware board support 64gb max ram and it has 4 slots

But I have 64gb(2x32gb) that I wish so much That I can use it with the board

Is there a way I can mod the bios to support more than 16 GB per slot? 

Btw, I can access the bios hidden menus in UEFI bios editor

**Comment by mojarrah** [comment]
@Electron-PSO it would be insanely helpful if we can do it

**Comment by Electron-PSO** [comment]
The CPU has a 4 channel memory controller.  

For best results, I would stick with 4 x 16GB sticks. 

There may be a way to get around the limit, but is it worth it?

**Comment by mojarrah** [comment]
@Electron-PSO its worth it for me

I is a way to enable it?
