### ISSUE TITLE
I have a 3gb gtx 780 will rebar take it?

### ISSUE THREAD

**Issue by loverayde** [xCuri0/ReBarUEFI#104]
**System**
 - Motherboard:
 - BIOS Version:
 - GPU:  GTX 780
 - [x ] CSM is turned off
 - [x ] 4G decoding is enabled
 - [ x] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [n ] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

Describe the issue here.

**Comment by xCuri0** [comment]
No but see #89 if you really want it and are willing to compile and try experimental stuff
