### ISSUE TITLE
MSI Z97 Gaming 3 is listed as compatible but not work

### ISSUE THREAD

**Issue by selver1** [xCuri0/ReBarUEFI#113]
**System**
 - Motherboard: MSI Z97 GAMING 3
 - BIOS Version: AMI BIOS2.A
 - GPU: PowerColor Red Dragon Radeon RX 580 8GB
 - [ x] CSM is turned off. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [ x] 4G decoding is enabled. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [ ] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [ ] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

Describe the issue here.

Hello,

In the list here the MSI Z97 Gaming 3 is listed as compatible and that it doesn't need a UEFI mod to activate Resizable BAR, so I only have to activate the hidden 4G decoding. I did that with modGRUBShell.efi ( setup_var 0x1 0x1 ) but unfortunately it didn't work. The first problem is that the bios remains completely black, meaning I can't get in anymore. When Windows starts, Resizable BAR is still not activated. Can someone help me? I don't know what I'm doing wrong.

Best regards

**Comment by xCuri0** [comment]
Nowhere does it say you do not need UEFI modifications read the guide fully
