### ISSUE TITLE
2 PciBus DXE drivers found in UEFITool search, unable to use UEFIPatch

### ISSUE THREAD

**Issue by Epikest** [xCuri0/ReBarUEFI#117]
**System**
 - Motherboard: Asus ROG STRIX B550-F GAMING (WI-FI)
 - BIOS Version: 3404 (2023/10/31)
 - GPU: EVGA XC HYBRID GAMING GeForce RTX 2080 Ti 11 GB Video Card
 - [X] CSM is turned off. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [X] 4G decoding is enabled. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [ ] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [X] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**
header search for PciBus returns 2 results:
![image](https://github.com/xCuri0/ReBarUEFI/assets/45499416/3cc68c68-9090-4731-840c-eee555ca14e6)
i added ReBarDxe.ffs to the end of both volumes and saved the image file. when i tried using UEFIPatch it complained and nothing happened to the file:
```
$ .\UEFIPatch.exe .\RB550FGW.CAP
parseImageFile: Aptio capsule signature may become invalid after image modifications
parseBios: one of volumes inside overlaps the end of data
parseBios: one of volumes inside overlaps the end of data
parseSection: GUID defined section with unknown processing method
parseSection: GUID defined section can not be processed
parseBios: one of volumes inside overlaps the end of data
parseBios: one of volumes inside overlaps the end of data
parseSection: GUID defined section with unknown processing method
parseSection: GUID defined section can not be processed
No patches can be applied to input file
```
i also tried using MMTool but PciBus was missing along with a lot of other stuff

**Comment by Black6spdZ** [comment]
> > and for Turing GPUs you need NvStrapsRebar not ReBarUEFI
> 
> what architecture is ReBarUEFI for?

everything that natively supports ReBar: 3060+

**Comment by xCuri0** [comment]
@Epikest Anything that supports resizable BAR

So NVIDIA 30 series and up.

For AMD anything Polaris or newer supports it despite AMD not mentioning it. Older cards AMD may work too but it's hard to find anyone with them.

For Turing 20/16 series you need to use NvStrapsRebar which does the additional configuration steps required on Turing GPUs

**Comment by Epikest** [comment]
> > > and for Turing GPUs you need NvStrapsRebar not ReBarUEFI
> > 
> > 
> > what architecture is ReBarUEFI for?
> 
> everything that natively supports ReBar: 3060+

> @Epikest Anything that supports resizable BAR
> 
> So NVIDIA 30 series and up.
> 
> For AMD anything Polaris or newer supports it despite AMD not mentioning it. Older cards AMD may work too but it's hard to find anyone with them.
> 
> For Turing 20/16 series you need to use NvStrapsRebar which does the additional configuration steps required on Turing GPUs

thanks
