### ISSUE TITLE
ASUS Z170-WS Semi-working with ReBAR

### ISSUE THREAD

**Issue by LatiosAeon** [xCuri0/ReBarUEFI#12]
**System**
 - Motherboard: ASUS Z170-WS
 - BIOS Version: 3062
 - GPU: RTX 3080 Ti FE

**Description**
The ReBAR module has been placed in the correct volume, it was extracted and replaced per instructions for "ASUS no boot after patching" but with the same failing result, the script appears to be working but only with 512MB, 1024MB and higher always results in the system completing POST checks but nothing more, no display or response, CSM disabled and above 4G Decode enabled but Resizable BAR enabled in BIOS also says No
![2022-11-07 (11)](https://user-images.githubusercontent.com/117758487/200622807-ed9a6841-4297-456d-9729-aaed97dcca3b.png)
[Z170WS_test.zip](https://github.com/xCuri0/ReBarUEFI/files/9963272/Z170WS_test.zip)

**Comment by xCuri0** [comment]
@LatiosAeon Try using UEFIPatch with the patches.txt from the UEFIPatch folder on it.

**Comment by LatiosAeon** [comment]
Ok, So I managed to figure out how to use UEFIPatch being as simple as drag and drop... and I've now only applied the patches.txt from the main file here and now its working, got the full 16GB BAR on the ARC A770, also done the same method to an ASUS Z170 Sabertooth MK1 and it now also has working ReBAR

**Comment by Rasmus715** [comment]
I understand it's been a while but maybe could you shared a modded Sabertooth bios, please?
