### ISSUE TITLE
Asus X99-A II Working ready to use file download and tutorial - unlocked NVram / modified pcibusdxe / injected rebardxe

### ISSUE THREAD

**Issue by Mak3rde** [xCuri0/ReBarUEFI#13]
EDIT:

Working Rebar with Unlimited Size.

Notice:

## MAKE THE BIOS BACKUP FIRST

- I would not recommend using afuwin to flash the uefi, my recommendation is clearly to use afuwin only for uefi backup.
- Flashing with the BIOS-FLASHBACK from the mainboard is easy and safe.
- Alternatively, you can flash the bioschip directly using a flasher, but this requires extra hardware and a second computer.

Tools: 
- MMtool
- uefitool
- uefipatch
- bios file

### ready to use efi Downloads:  
[X99-A-II-ASUS-2101_CAP_STOCKROM_64-bit_BAR_ENABLED_rebar_driver_injected_barsize_Patched.zip](https://github.com/xCuri0/ReBarUEFI/files/9989800/X99-A-II-ASUS-2101_CAP_STOCKROM_64-bit_BAR_ENABLED_rebar_driver_injected_barsize_Patched.zip)

[X99-A-II-ASUS-2101_ROM_STOCKROM_64-bit_BAR_ENABLED_rebar_driver_injected_barsize_Patched.zip](https://github.com/xCuri0/ReBarUEFI/files/9989804/X99-A-II-ASUS-2101_ROM_STOCKROM_64-bit_BAR_ENABLED_rebar_driver_injected_barsize_Patched.zip)

## If You want to diy 

###How To:

## 1 
- Download Latest Bios From Asus website 
- download MMtool, Uefi tool and uefipatch
- download patches.txt
- [patches_txt.zip](https://github.com/xCuri0/ReBarUEFI/files/9989839/patches_txt.zip)
- download rebardxe.ffs and pcibus.ffs 
- [X99-A-II-ASUS-2101_pciebusffs_rebardxeffs.zip](https://github.com/xCuri0/ReBarUEFI/files/9989850/X99-A-II-ASUS-2101_pciebusffs_rebardxeffs.zip)
- put all files in same directory 

## 2
- Open Mmtool, 
  - load Image -> ASUS_BIOS.CAP
  -  Replace Tab 
  -  scroll down until you find "Priebus" in Volume 02
  - click on pciebus
  -  look for "Module file" further up the window
  - now choose the pcibus.ffs by clicking on BROWSE
  -  click replace
 ### 2b
  -  switch to Insert Tab 
  -  look for "Module file" further up the window
  - now choose the rebar.ffs by clicking on BROWSE
  - directly below, enter "02" at Vol. index
  -  click insert
  
 ### 2c
 - click "save Image"
 -  close mmtool

 ## 3 
- download the atached patches.txt 

### OR

-create a new txt file  in you folder 
-  paste
#NVRAM whitelist unlock
54B070F3-9EB8-47CC-ADAF-39029C853CBB 10 P:0F84B300000041F6:90E9B300000041F6_
- replace the _ at the ende ( 1f6_) with a "Space "
- save file and close it.

## 4
- press Win+R on your Keyboard 
-  or start and search for cmd
- change directory to your folder  
- then type:  uefipatch BIOSFILENAME.CAP -o PATCHED_BIOS_FILENAME.CAP
- press enter

### A: 
- flash that cap file using the bios flashback feature 
### B: 
- open Efitool, load Patched .cap File 
- Click -> Action -> Capsule -> Extract body -> save as .bin or .rom
- flash to bios 

**System**
 - Motherboard: Asus X99A-2 (X99-A II)
 - BIOS Version: 2101 (type: UEFI)
 - GPU: PowerColor AMD Radeon RX 6950 XT
 - Operating System: Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)

**Comment by xCuri0** [comment]
Hi the problem here is with NvramSmi not allowing EFI variables to be written. Other users were able to fix this by downgrading NvramSmi or BIOS with one from 2014.

A patch needs to be developed for your NvramSmi to remove the variable name restriction. I do think those on Hackintosh forums have already figured it out.

**Comment by Mak3rde** [comment]
Thx for that info, i will look into it until i got it working and post a how to here.

**Comment by Mak3rde** [comment]
Got it working partially, need to patch the above 1gb restriction it seems

# NVRAM whitelist unlock
54B070F3-9EB8-47CC-ADAF-39029C853CBB 10 P:0F84B300000041F6:90E9B300000041F6

**Comment by Mak3rde** [comment]
@xCuri0 got it working.

edited initial post.

**Comment by xCuri0** [comment]
your patch for PciBus has been added in commit [16712446c800707822dc4e37964abe0c85fc6e50](https://github.com/xCuri0/ReBarUEFI/commit/16712446c800707822dc4e37964abe0c85fc6e50)

**Comment by Mak3rde** [comment]
@xCuri0  nice!

Maybe you should add the info that this patch is specifically for the Asus X99a-II because the other patch that already was in the patch.txt and had Haswell written to it wasn't working on my bios, so I would assume thy my patch won't work on other platforms too. Maybe it's working for other Asus x99 boards, but I could test that.

**Comment by xCuri0** [comment]
@Mak3rde actually it does seem to apply to an ASUS Z170-WS board with similar issue. waiting to see if it works for them

**Comment by dawenhaozx** [comment]
Thank you very much for your efforts to fix this issue.
I tried it but it didn't work.

setup_var_cv IntelSetup 0x10E2 0x04 0x00(0x00~0x07)



0x11339 	VarStore: VarStoreId: 0x1 [EC87D643-EBA4-4BB5-A1E5-3F3E36B20DA9], Size: 0x17D6, Name: IntelSetup {24 21 43 D6 87 EC A4 EB B5 4B A1 E5 3F 3E 36 B2 0D A9 01 00 D6 17 49 6E 74 65 6C 53 65 74 75 70 00}

0x15351 		One Of: MMIOHBase, VarStoreInfo (VarOffset/VarName): 0x10E2, VarStore: 0x1, QuestionId: 0x1A8, Size: 4, Min: 0x0, Max 0x7, Step: 0x0 {05 9A 0C 00 0D 00 A8 01 01 00 E2 10 10 12 00 00 00 00 07 00 00 00 00 00 00 00}
0x1536B 			One Of Option: 56T, Value (32 bit): 0x0 (default) {09 0A 14 11 32 02 00 00 00 00}
0x15375 			One Of Option: 40T, Value (32 bit): 0x1 {09 0A 13 11 02 02 01 00 00 00}
0x1537F 			One Of Option: 24T, Value (32 bit): 0x2 {09 0A 12 11 02 02 02 00 00 00}
0x15389 			One Of Option: 16T, Value (32 bit): 0x3 {09 0A 11 11 02 02 03 00 00 00}
0x15393 			One Of Option: 12T, Value (32 bit): 0x4 {09 0A 10 11 02 02 04 00 00 00}
0x1539D 			One Of Option: 4T, Value (32 bit): 0x5 {09 0A 0F 11 02 02 05 00 00 00}
0x153A7 			One Of Option: 2T, Value (32 bit): 0x6 {09 0A 0E 11 02 02 06 00 00 00}
0x153B1 			One Of Option: 1T, Value (32 bit): 0x7 {09 0A 0D 11 02 02 07 00 00 00}

**Comment by xCuri0** [comment]
@dawenhaozx have you verified that the address is actually changing in Windows

Because iirc there are multiple entries for each PCIe port.

Also there's an option to change the MMIOH region size (default 256GB) which you can try changing.

**Comment by revelator** [comment]
decided to try this out on my asus x99-A II but i cannot flash the bios neither by bios flashback nor ezflash.
bios flashback just blinks once then stops and it does work when i try to flash the original bios.
ezflash throws an error :/
even tried the built in flasher in the bios but it complains saying that it is not an uefi bios.

my guess is im one of the unlucky ones that have an encrypted bios that checks everything ?.
my question would be if downgrading the bios via flashback to an older version would help.

**Comment by medenijazbec** [comment]
seems a bit late, dont know if you have already solved it, but this dude did the same thing here, but instead of flashing .cap he just simply extracted it into a .rom
https://forum.level1techs.com/t/x99-e-10g-ws-post-issues-3x-p40-llm-inference-rig/211715

**Comment by revelator** [comment]
tbh none of my two x99 boards would accept any of the prebuilt caps made for them. i also have an x99 deluxe which i recently delegated to developer work. the A II was sold and upgraded with a rog strix x570 board and 3700x cpu which supports rebar from the get go. sadly the old cabinet i use for the deluxe has no space for my 2080 ti which also needs hacks to support rebar so i had to use my rtx 3070 in that one instead.
