### ISSUE TITLE
Damage Report, Asrock Z370 Extreme4 killed after play Cyberpunk 2077.

### ISSUE THREAD

**Issue by Daishuku** [xCuri0/ReBarUEFI#136]
**System**
 - Motherboard: Asrock Z370 Extreme4
 - BIOS Version: 4.21B
 - GPU: Saphhire RX 6900XT Nitro+
 - [ Y ] CSM is turned off. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [ Y ] 4G decoding is enabled. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [ N ] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [ N ] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

Just report, in case the guy never visit github. I Quote he sentence on web. 
Checklist he answered above.

He basic success the ReBAR mod with 256MB (known issue has no Coffee Lake related and No Patch applied is okay in this case)

Playing Forza Horizon 5 is okay, however when playing Cyberpunk 2077, PC black out when visit some scene. When try disable ReBAR on BIOS, the PC keep instant black out and unable to boot. Already try clean CMOS. He need remove ATX12V to keep motherboard running. Sounds like CPU get trouble.

**Comment by xCuri0** [comment]
Module does nothing when set to 256mb, this is either UEFITool caused corruption or a hardware issue
