### ISSUE TITLE
2 GUID patterns instead of one

### ISSUE THREAD

**Issue by Geromo94** [xCuri0/ReBarUEFI#139]
**System**
 - Motherboard: ASROCK B550M Pro4
 - BIOS Version: P3.40
 - GPU: Nvidia GTX 1650
 - [ + ] CSM is turned off. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [ +  ] 4G decoding is enabled. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [ - ] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [ + ] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

Hello, i am try open my latest downloaded BIOS ROM from official site ASROCK, but after search GUID, i founded 2 patter instead of 1 pattern.  What am I supposed to do? :(

![image](https://github.com/xCuri0/ReBarUEFI/assets/37875880/d84e0e44-4a4c-4387-a689-3a5f945480d2)

Links:
— https://download.asrock.com/BIOS/AM4/B550M%20Pro4(3.40)ROM.zip

**Comment by xCuri0** [comment]
Add to both
