### ISSUE TITLE
ReBar.ffs missing after successful BIOS Flash

### ISSUE THREAD

**Issue by crqzys70rm** [xCuri0/ReBarUEFI#187]
**System**
 - Motherboard: TUF B450M-PRO GAMING
 - BIOS Version: TUF B450M-PRO GAMING BIOS 4401
 - GPU: Dell RTX 2080 Ti OEM
 - [✔] CSM is turned off. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [✔] 4G decoding is enabled. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [✔] <strike>UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed</strike>
 - [✔] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

I followed the necessary steps until a successful BIOS flash.
Then, I ran NvStrapsReBar.exe and executed the essential commands (E>S>Q>reboot).
However, despite these efforts, Rebar remains disabled.
Upon investigation, I noticed that the UEFI DXE driver status is showing as "Not loaded" (0x000000000000000A).
![image](https://github.com/terminatorul/NvStrapsReBar/assets/145791371/18d61092-660a-49bc-9f29-d03c1107a316)

In an attempt to resolve this, I tried running AFUDOS to obtain the current BIOS backup.
Unfortunately, there was no NvStrapsReBar.ffs found on the backup BIOS ROM.
![image](https://github.com/terminatorul/NvStrapsReBar/assets/145791371/7c2e3eba-12f1-4562-b444-7fdc867a5db4)

To address this, I attempted to rebuild the BIOS file by adding the NvStrapsReBar.ffs, but the outcome remained unchanged: UEFI DXE driver status still showed "Not loaded", and Rebar remained disabled.
I repeated the process of running AFUDOS to acquire the BIOS backup, but once again, there was no NvStrapsReBar.ffs present on the backup BIOS ROM.

At this point, I'm unsure of what to do next. Any assistance you could provide would be greatly appreciated. Thank you.

**Comment by xCuri0** [comment]
Wrong place to report this issue
