### ISSUE TITLE
"Video Scheduler Error" BSODS

### ISSUE THREAD

**Issue by Tykwha** [xCuri0/ReBarUEFI#188]
Well, this may be a little off topic, but after flashing the laptop using NvStrapsRebar project, and activating Rebar, it worked, but immediately after loading Windows I get an error "Video Scheduler Error".  Does anyone have any ideas or tips?

Ryzen 7 4800h with Vega graphics
RTX2060

**Comment by xCuri0** [comment]
wrong place to ask this
