### ISSUE TITLE
EFI Error (at Create Timer) (0x01001202000000B4)

### ISSUE THREAD

**Issue by mrlmao** [xCuri0/ReBarUEFI#191]
**System**
 - Motherboard: H61M-DS2
 - BIOS Version:F7
 - GPU: MSI Gtx 1660 Super Gaming-x
 - [x] CSM is turned off. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [x] 4G decoding is enabled. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [x] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [x] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

Describe the issue here.

**Comment by mrlmao** [comment]
![image](https://github.com/xCuri0/ReBarUEFI/assets/164392129/e7baba2e-8c71-467b-a105-eab9e19ea06a)
I cant turn on rebar

**Comment by mrlmao** [comment]
![image](https://github.com/xCuri0/ReBarUEFI/assets/164392129/f26eb4e4-1fe8-46fe-b426-fdebc86aee20)

**Comment by xCuri0** [comment]
Wrong repo open in NvStrapsRebar instead


Also 64GB BAR won't work and isn't needed for a 1660 u only need 8GB
