### ISSUE TITLE
ReBar not working on Asus B450F.

### ISSUE THREAD

**Issue by Artasdmc** [xCuri0/ReBarUEFI#205]
Windows 11
 - Motherboard: Asus B450F
 - BIOS Version: 5404 (AGESA version to ComboV2PI 1.2.0.Ca)
 - GPU: Nvidia RTX 2070 Super
 - CSM is turned off. 
 - 4G decoding is enabled
 - UEFIPatch is applied

This motherboard does not support bios flashback, originally used AFUDOS to force a bios flash. Which in turn just bricked my motherboard. Now I'm back with modified bios which I flashed with CH341A, DXE Driver is included and recognized.

Motherboard has 2 options for ReBar (Off/Auto), no matter the setting ReBar is still not working. Rebar is set to 4GB with your tool.

![Screenshot (7)](https://github.com/xCuri0/ReBarUEFI/assets/11082425/8a94f0a3-ddd9-41be-ba89-0dbc6c5f1224)
![Screenshot (8)](https://github.com/xCuri0/ReBarUEFI/assets/11082425/85cb1403-eb67-4dca-b6df-11157e710560)

**Comment by xCuri0** [comment]
You have to use NvStrapsRebar on Turing, not ReBarUEFI

**Comment by Artasdmc** [comment]
My mistake, I'll be right back to confirm.

**Comment by Artasdmc** [comment]
Just reset BIOS, enabled Rebar which disables CSM and enabled 4G decoding, and loaded in to windows. I'm getting an error that the driver has not been loaded, even though it was flashed with modified BIOS.

I'm attaching bios file I used to flash my motherboard. Does location matter where it is added?
It is there, just by searching nvs you can find it in uefitool.
[bios.zip](https://github.com/xCuri0/ReBarUEFI/files/14971788/bios.zip)

**Comment by Artasdmc** [comment]
This board got ReBar support with BIOS 4007 which also added new CPUs with it. Could maybe roll back to that, but I'm giving away all security updates with it.
