### ISSUE TITLE
asus x99 deluxe Bios file with modify resizable bar 

### ISSUE THREAD

**Issue by markmark2009** [xCuri0/ReBarUEFI#21]
**System**
 - Motherboard: asus x99 deluxe
 - BIOS Version: 4101
 - GPU: RTX 3080Ti 
 - I tried this on my motherboard but it doesn't work. Does anyone have a Bios file with modify resizable bar enabled for asus x99 deluxe? 
 Thanks MARK-PC

**Comment by xCuri0** [comment]
All of the instructions are in README and wiki. Several others have it working on ASUS X99 motherboards and issues isn't for support.

I don't do BIOS mod requests but you could try win-raid forum or somewhere else if anyone else wants to.
