### ISSUE TITLE
B85 Chipset Motherboard Patch DSDT

### ISSUE THREAD

**Issue by localhosts-A** [xCuri0/ReBarUEFI#231]
I have added above 4g decoding support to the Gigabyte H81M-DS2 and biostar B85S3+ motherboards after making changes based on an article, but both require replacing the pcibus and the PciHostBridge, my question is on the B85/H81 motherboards that don't have above 4g decoding support according to the My question is whether dsdt patching on a B85/H81 motherboard without above 4g decoding support can enable above 4g decoding according to the guide on the wiki.

**Comment by wjy8969** [comment]
ASUS B85M-G Here.
How did it turn out?
I really need it ！！！！
Thanks.

**Comment by localhosts-A** [comment]
> 我是华硕B85M-G。结果怎么样？我真的很需要!!!谢谢。



> ASUS B85M-G Here. How did it turn out? I really need it ！！！！ Thanks.

It worked

**Comment by Koekieezz** [comment]
> > 我是华硕B85M-G。结果怎么样？我真的很需要!!!谢谢。
> 
> 
> 
> > ASUS B85M-G Here. How did it turn out? I really need it ！！！！ Thanks.
> 
> It worked

@localhosts-A would you mind to tell us how you add above 4g decoding and working for 8 series motherboards? I have some Gigabyte B85 bioses that has above 4g decoding option BUT it just not working, so the switch is in the bios, but still not working.

**Comment by localhosts-A** [comment]
> [@localhosts-A](https://github.com/localhosts-A) would you mind to tell us how you add above 4g decoding and working for 8 series motherboards? I have some Gigabyte B85 bioses that has above 4g decoding option BUT it just not working, so the switch is in the bios, but still not working.

If your motherboard has hidden options, you can try following the wiki to patch it, which might help. If that doesn't work, I tried flashing the BIOS from a Z97 motherboard from the same manufacturer and then patching it.

**Comment by localhosts-A** [comment]
> > [@localhosts-A](https://github.com/localhosts-A) would you mind to tell us how you add above 4g decoding and working for 8 series motherboards? I have some Gigabyte B85 bioses that has above 4g decoding option BUT it just not working, so the switch is in the bios, but still not working.
> 
> If your motherboard has hidden options, you can try following the wiki to patch it, which might help. If that doesn't work, I tried flashing the BIOS from a Z97 motherboard from the same manufacturer and then patching it.

Z87, not Z97
