### ISSUE TITLE
Bios is in .exe formate

### ISSUE THREAD

**Issue by Musa-Irfan** [xCuri0/ReBarUEFI#233]
I tried to extract it but it dosent work my mother board is the xps 8500 here is the bios https://dl.dell.com/FOLDER05052628M/1/A14.EXE

**Comment by Musa-Irfan** [comment]
i tried it again now its saying command line parameter is not correct

**Comment by localhosts-A** [comment]
Dell's bios seems to require special software to decompress, on Github there are

**Comment by localhosts-A** [comment]
Or try to extract it directly from the machine?
Use a programmer or software

**Comment by localhosts-A** [comment]
https://github.com/vuquangtrong/Dell-PFS-BIOS-Assembler

**Comment by Musa-Irfan** [comment]
oh wow lemme try that

**Comment by Musa-Irfan** [comment]
oh how do i use that assembler

**Comment by localhosts-A** [comment]
I don't know, I've only used it on a Dell 5559

**Comment by Musa-Irfan** [comment]
I Tried using 7 zip and i get a file called FFFFFFFF[VOL] is this the bios?

**Comment by Musa-Irfan** [comment]
nvm i used uefi tool on this and it worked and i found pcie bus thanks everyone
