### ISSUE TITLE
error when i apply the patches in cmd

### ISSUE THREAD

**Issue by ricardohvt** [xCuri0/ReBarUEFI#245]
**System**
 - Motherboard: PRIME-H510M-E-ASUS
 - BIOS Version: 05/07/2022 (1601)
 - GPU: Asus RTX 2060 Evo OC 6GB
 - [ On ] CSM is turned off. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [ On ] 4G decoding is enabled. **Make sure to confirm this in the BIOS and not with GPU-Z or similar since it can be inaccurate**
 - [ No ] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [ Yes ] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

Desc: 
In CMD/PowerShell, i got this error when i apply the patches:
C:\Users\pc\Desktop\UEFIPatch_0.28.0_win32>UEFIPatch PRIME-H510M-E-ASUS-2402rebar.rom
parseImageFile: Aptio capsule signature may become invalid after image modifications
parseBios: one of volumes inside overlaps the end of data
parseBios: one of volumes inside overlaps the end of data
parseBios: one of volumes inside overlaps the end of data
parseFile: non-empty pad-file contents will be destroyed after volume modifications
No patches can be applied to input file
![image](https://github.com/user-attachments/assets/c9505734-9d15-4e8a-8749-6761f3680940)

Also, i got a question too, my original BIOS File is .CAP, when i use UEFITool i got .rom, have any issue about it???

HWinfo
![image](https://github.com/user-attachments/assets/9fb3bfff-f9cb-443b-add6-782b5f56dffd)

**Comment by xCuri0** [comment]
Nothing to apply just ignore the errors

**Comment by ricardohvt** [comment]
@xCuri0 also, my bios doesnt support .rom files (doesnt show in his file explorer), only .CAP, how i make the bios mod file to .CAP?
Also, my bios got Asus Bios Rollback Support, if i have any issue in my bios, how i do it??
