### ISSUE TITLE
Resizable Bar Sucessfull on ASUS Z68 Chipset

### ISSUE THREAD

**Issue by TheC41R0N11** [xCuri0/ReBarUEFI#259]
![Rebar 1155 2](https://github.com/user-attachments/assets/f78fe701-2cc7-485b-be01-1bfacbb152e4)
![8GB Bar](https://github.com/user-attachments/assets/6d3af02f-a285-4e69-a758-0ecfbca2a3c1)
![Rebar 1155 3](https://github.com/user-attachments/assets/94ab1990-f6a9-4eee-bf25-0819b450b6fe)
![Rebar 1155](https://github.com/user-attachments/assets/a4b4510c-386a-49ba-86b3-75d280502d1b)

Motherboard: ASUS P8Z68-V LX
GPU: AMD Radeon RX 6600 8GB 
UEFIPatch: YES
DSDT Patch: YES
BAR Size: 8GB
RAM: 32GB
Requires DSDT Modification (Manual just as shown by User: [gastovskialpha1](https://github.com/gastovskialpha1))

**Comment by Gumka77** [comment]
Nice. Can I have more details please? I have ASUS P8Z68-V Pro and Radeon RX 590.
