### ISSUE TITLE
Asus ROG STRIX Z270-I GAMING

### ISSUE THREAD

**Issue by KuRue** [xCuri0/ReBarUEFI#27]
MB: Asus ROG STRIX Z270-I GAMING
CPU: 7700K
GPU: RTX 3080
RAM: 16GB

With the latest BIOS for my motherboard (Version 2001), I added ReBarDxe and unencapsulated using UEFITool.
I flash the modified BIOS with AFUWin64 as described in the linked guide, enable 4G decoding and disable CSM.
BAR at 256MB
![image](https://user-images.githubusercontent.com/1352930/210026057-d2a06a79-5b73-44b0-b3c9-f03a0242087d.png)
BAR at 1024MB - Only iGPU posts, Freeze at BIOS logo, removing GPU boots back into Windows.
BAR at Unlimited - Only iGPU posts, Bluescreen at during boot, Stop code: WDF VIOLATION

I repeated this with UEFIPatch and the linked patches.txt and checked for page-files (there are none), and I get the same results.

I'm currently trying DSDT patching but the only thing under Large Memory is: 
[0000002000000000 - 0000002FFFFFFFFF] PCI Express Root Complex
And I am not able to find AmiBoardInfo using UEFITool.

Guidance or incite would be greatly appreciated.

**Comment by xCuri0** [comment]
@KuRue does 512MB BAR work ?

also post a screenshot of device manager resourcing showing the GPU (when its working)
like this 
![image](https://user-images.githubusercontent.com/29529557/210031063-5634b815-56fe-4dcb-8618-abc1c0de8b03.png)

**Comment by xCuri0** [comment]
@KuRue when i run uefipatch it finds and patching
![image](https://user-images.githubusercontent.com/29529557/210031574-4df95eb2-f863-498d-a2e8-96a4afd8366e.png)

it should fix it because what you describe is exactly what happens without **Don't downgrade 64-bit BARs to 32-bit** patch

**Comment by KuRue** [comment]
After patching and flashing again it looks like it's working correctly. I must not have saved patches.txt after replacing the text 🤦‍♂️. 
Setting BAR to unlimited shows BAR1 at 16GB and everything shows Yes or Enabled in GPU-Z now.

Thank you for the help and great work!
