### ISSUE TITLE
Asus Z270-A Prime - ReBarState doesn't enable ReBar

### ISSUE THREAD

**Issue by WillyTP** [xCuri0/ReBarUEFI#28]
**System**
 - Motherboard:  Asus Z270-A
 - CPU: i7700K
 - BIOS Version: 1302
 - GPU:  Intel ARC380
 - [X] CSM is turned off
 - [X] 4G decoding is enabled
 - [N] UEFIPatch is applied (see README for more information)
 
**Description**
I modded the BIOS and flashed it via Asus AI Suite (all the other methods didn't work).
PC posts properly, however after running ReBarState.exe and rebooting into GPU-Z ReBar status is still disabled.

Are there some further checks I may do?

1. I'd like to know if new BIOS has really been flashed properly (I've got no errors, however I can't be sure)
2. Something else?

Thanks for help

[PRIME-Z270-A-ASUS-1302-ReBar.zip](https://github.com/xCuri0/ReBarUEFI/files/10419392/PRIME-Z270-A-ASUS-1302-ReBar.zip)

**Comment by xCuri0** [comment]
@WillyTP does disabling secure boot help ?

maybe @KuRae (ASUS ROG Z270-I) can help because this UEFI layout is weird to me

**Comment by WillyTP** [comment]
Hi @xCuri0 , thanks for support.
Unfortunately disabling Secure Boot has made no effects.

If anyone of you have some suggestion to what to do / further check is welcome.

Kind regards

![ReBarStatus](https://user-images.githubusercontent.com/15254201/212538142-768144f3-c28c-4f70-ae71-ef5712ba9580.gif)
![ReBarState](https://user-images.githubusercontent.com/15254201/212538147-160cd321-ea0f-4e97-8c4a-968a10ba39c7.jpg)

**Comment by xCuri0** [comment]
@dsanke UEFI layout on Z270 seems weird I saw you had it working on a Z270 board did anything have to be done differently ?

**Comment by dsanke** [comment]
@xCuri0 I guess there isn't a successful BIOS mod, the Ai Suite won't flash unofficial BIOS.

**Comment by WillyTP** [comment]
Hi @dsanke, thanks for your support.

Just for being clear: in order to flash the Bios you posted, is it OK via EZ Flash or shall I proceed through other ways?
For setting Bios Lock disabled, what do you mean exacly? Removing Secure Boot?

Thank you

**Comment by dsanke** [comment]
> is it OK via EZ Flash or shall I proceed through other ways?
No you can't use any official flash method. You can use SPI Programmer hardware to read backup and write modified BIOS. Or follow the thread I have linked before. Set BIOS Lock first and use Intel FPT read backup and flash modified BIOS.
> For setting Bios Lock disabled, what do you mean exacly?
Go and see the winraid forum link above.
> Removing Secure Boot?
Yes in order to set BIOS Lock disabled it should be disabled.

**Comment by WillyTP** [comment]
Hi @dsanke, thanks for your support.
Unfortunately now I don't have time for such a complicated process, however your help has been very appreciated.
One more question for you if you've time to tell:
I've checked with UEFITool the Bios you modded, and I've seen you've inserted Rebar under a different section than mine (I put it at the bottom of the section with all DXE drivers).
Why?

Thank you

**Comment by dsanke** [comment]
@WillyTP It might be my mistake because I modified these BIOS using script, I modified all ASUS 100/200 series BIOS.
Will correct it.

**Comment by nook24** [comment]
I also have an Asus Z270-A with an Intel i7700k. Were you able to successfully patch the BIOS?

**Comment by WillyTP** [comment]
Hi @nook24
Unfortunately I haven't had the time to flash the one provided by @dsanke due to the complex procedure to do (lack of time)

Should be able to, please let me know how you manage it.

Thank you

**Comment by WillyTP** [comment]
Hi @nook24 , everyone
I've been able to flash modded bios, even tough now I cannot check ReBar functionality since I changed GPU with a GTX 1660 Super.

Anyway, procedure has been smoother than what I tought.
I quickly resume in a few points:

1. Download Intel FPT and tools package from link [above](https://winraid.level1techs.com/t/guide-grub-fix-intel-fpt-error-280-or-368-bios-lock-asus-other-mod-bios-flash/32725)
2. Backup current BIOS (FPTw -bios -d backup.bin)
3. Mod backupped bios
4. Disable Secure Boot
5. Disable Bios Lock via EFI shell (0x90C -> 0x00)
6. Flashe new BIOS (fptw -bios -f Z170A_ModdedBackup.bin)

Kind regards

**Comment by nook24** [comment]
Thanks for your replay. Unfortunately I'm always ending up with the `Pad-File` issue when i try to modify my BIOS, even if i go the MMTool route.

So I'm not going to try to flash my patched bios as i can not risk to brick this system.

**Comment by xCuri0** [comment]
@WillyTP this is an issue that happens when flashing with ASUS AI Suite. See #42 

You need to use another method such as afuwin/afudos

**Comment by OmgStreaker** [comment]
> @xCuri0 Seen some TE image not aligned? I guess there isn't a successful BIOS mod, I think the Ai Suite won't flash unofficial BIOS. Follow this: https://winraid.level1techs.com/t/guide-grub-fix-intel-fpt-error-280-or-368-bios-lock-asus-other-mod-bios-flash/32725 The offset of BIOS Lock is 0x90C, and I have modified BIOS provided below. This BIOS have ReBAR default enabled so you dont need use ReBarState. Set BIOS Lock disabled and backup your BIOS then flash the modified BIOS I provided. Just flash BIOS Region, the Flash Descriptor and ME Region need more operation to write. This BIOS can support Coffee Lake when you flash Flash Descriptor and ME Region(and need pin mod for U0/P0/R0 step CFL CPU), but I guess you don't need that. [PRIME-Z270-A-ASUS-1302.zip](https://github.com/xCuri0/ReBarUEFI/files/10433959/PRIME-Z270-A-ASUS-1302.zip)

Can someone plz help me patching my z170 pro gaming bios? (intel i7 6700k)

**Comment by OmgStreaker** [comment]
Anyone ?

**Comment by dsanke** [comment]
[Z170-PRO-GAMING-ASUS-3805.zip](https://github.com/xCuri0/ReBarUEFI/files/13331356/Z170-PRO-GAMING-ASUS-3805.zip)
@OmgStreaker

**Comment by OmgStreaker** [comment]
> [Z170-PRO-GAMING-ASUS-3805.zip](https://github.com/xCuri0/ReBarUEFI/files/13331356/Z170-PRO-GAMING-ASUS-3805.zip) @OmgStreaker

Thankyou so much bro but i mod it myself yesterday 😁

**Comment by OmgStreaker** [comment]
Now, i have new issues on the way 🥲
