### ISSUE TITLE
resizable BAR not included

### ISSUE THREAD

**Issue by Alloinkil** [xCuri0/ReBarUEFI#29]
**System**
 - Motherboard: plexHD x99
 - BIOS Version:n/a
 - GPU: s7000 (r7 370x)
 - [ ✓] CSM is turned off
 - [✓ ] 4G decoding is enabled
 - [ ✓] UEFIPatch is applied (see README for more information)
 
**Description**

Describe the issue here. 
![2j3](https://user-images.githubusercontent.com/122085811/214322010-96d2ff52-0f77-4253-81a6-f0216f67aefd.png)

Hi everyone.  I did everything as described in the faq several times, but rebar did not turn on.  I am using a modified driver from nimez but still nothing works.

**Comment by xCuri0** [comment]
@Alloinkil Polaris and some R9 cards still have it supported at the VBIOS/hardware level. The registry edit just allows the driver to use that
