### ISSUE TITLE
MSI z270-A Pro | Can't find the correct string in the BIOS

### ISSUE THREAD

**Issue by Gabus1983** [xCuri0/ReBarUEFI#34]
**System**
 - Motherboard: MSI z270-A Pro 
 - BIOS Version: 1.60
 - GPU: RTX 3080
 - [Y] CSM is turned off
 - [Y] 4G decoding is enabled
 - [N] UEFIPatch is applied (see README for more information)
 
**Description**

Using UEFITool I searched for the PciBus string (text/unicode) and got several results, of which I am not sure which one is the correct one.
![image](https://user-images.githubusercontent.com/126199805/221015669-31e2a822-b107-46a4-a034-86ba41422b01.png)
The tutorial mentions "insert the FFS module at the end of the volume".

In that part of the BIOS it says "section", there are also "files", but that part is not a volume...

[The original BIOS file is this one](https://download.msi.com/bos_exe/mb/7A71v16.zip)

Can you help me find the right place to insert the module?

I have seen that there are other users with MSI z270 and ASUS z270, so I guess it could be possible to insert it correctly and make it work.

TIA

**Comment by Gabus1983** [comment]
Hello @triple-octopus , I saw you have succesfully patched a _MSI Z270 GAMING M5_... can you help? Thanks

**Comment by triple-octopus** [comment]
Absolutely, I have a patched BIOS file ready if you need it

**Comment by Gabus1983** [comment]
> 
Thank you! 
I saw you have a Z270 M5, mine is a Z270-A PRO...  I think the edited part would be similar...

**Comment by xCuri0** [comment]
@Gabus1983 both seem to be in the same module. just insert it at the end of the volume that the module is in

**Comment by Koekieezz** [comment]
@Gabus1983 you could try this for your Z270-A Pro
[Z270AProMOD.zip](https://github.com/xCuri0/ReBarUEFI/files/10831764/Z270AProMOD.zip)

Here is your above 4g decoding offset (if its not visible on bios)
![image](https://user-images.githubusercontent.com/112951868/221369459-0f75f35d-f9d5-417a-83a5-d67a445690a7.png)

**Comment by Gabus1983** [comment]
First of all, @Koekieezz, thank you very much.
The flash through M-Flash was successful. 
I saw that you edited the version, it showed it as **1.61**. It even changed the MSI logo on the boot (I almost had a syncope!).

**Testing:**
With the edited BIOS it doesn't keep the settings saved, they go back to default, therefore, I can't enable the 4G decoding option (the original BIOS shows it).
Another strange thing is that when reading OC profiles it does not read them correctly either, only some partial options. 

But since you gave me an edited BIOS I could understand where to insert the module. I compared where you did it and did it the same way.
Second (I really don't know if it was necessary but I did it anyway) I did the UEFI Patching.

I flashed the BIOS again and this time it kept the OC and other options. As the 4G decoding option was already enabled, I proceeded to apply the DXE driver.

**Result: Enabled**

![image](https://user-images.githubusercontent.com/126199805/221391633-e17ea285-8bef-4009-89af-63a49215ba78.png)

**Comment by Koekieezz** [comment]
> First of all, @Koekieezz, thank you very much. The flash through M-Flash was successful. I saw that you edited the version, it showed it as **1.61**. It even changed the MSI logo on the boot (I almost had a syncope!).
> 
> **Testing:** With the edited BIOS it doesn't keep the settings saved, they go back to default, therefore, I can't enable the 4G decoding option (the original BIOS shows it). Another strange thing is that when reading OC profiles it does not read them correctly either, only some partial options.
> 
> But since you gave me an edited BIOS I could understand where to insert the module. I compared where you did it and did it the same way. Second (I really don't know if it was necessary but I did it anyway) I did the UEFI Patching.
> 
> I flashed the BIOS again and this time it kept the OC and other options. As the 4G decoding option was already enabled, I proceeded to apply the DXE driver.
> 
> **Result: Enabled**
> 
> ![image](https://user-images.githubusercontent.com/126199805/221391633-e17ea285-8bef-4009-89af-63a49215ba78.png)

yes it was due to the RTK dxe, you could replace it using the ver 2.57 ones, the 2.59 ones quite didnt work on my previous msi bios (Z68, same symptomps as yours).

For the logo i was actually trying to extract the logo from your bios (for collection purposes) but ig my eyes n brain were just sloppy enough that i replaced the logo that i have (it was from MSI ACE series with modern msi logo)

**Comment by Gabus1983** [comment]
@Koekieezz @xCuri0, thanks!
