### ISSUE TITLE
Enabling 4G decode makes boot drives disappear on ASRock H110M-DVS R3.0  

### ISSUE THREAD

**Issue by glikched** [xCuri0/ReBarUEFI#35]
![image](https://user-images.githubusercontent.com/80767544/221429015-e41baf2f-f9ae-4966-93b0-0fa804268a22.png)

I tried Extracting the dsdt included in to this DXE driver but failed.

[bios](https://mirror.rex-drive.workers.dev/0:/rebar.fd?a=view)

**Comment by glikched** [comment]
I am trying that way as after i enable Above 4G it can't see sata drives.

**Comment by xCuri0** [comment]
@glikched you gave zero information about your system

And the issue with drives not showing is because you installed windows in legacy mode. the wiki common issues says how to fix it

**Comment by xCuri0** [comment]
@glikched Does Linux boot with above 4G decode on ? DSDT patch won't fix the issue you have, if the drive doesn't show in the BIOS it's probably some legacy option being on

**Comment by glikched** [comment]
It doesn't

**Comment by glikched** [comment]
Sir. I don't want to harm but i said i have everything set on uefi mode. I will send you some pitrures after i setup_var 0x377 0x1 again.

**Comment by xCuri0** [comment]
Wiki now has instructions for extracting and reinserting DSDT on these boards. One user on win-raid was successful doing it

**Comment by glikched** [comment]
Ok thank i didn't got time to check and give you more info.

**Comment by dormancygrace** [comment]
> ![image](https://user-images.githubusercontent.com/80767544/221429015-e41baf2f-f9ae-4966-93b0-0fa804268a22.png)
> 
> I tried Extracting the dsdt included in to this DXE driver but failed.
> 
> [bios](https://mirror.rex-drive.workers.dev/0:/rebar.fd?a=view)

First of all, you need raw section from DsdtAsl. You should search>GUID>header only

**Comment by xCuri0** [comment]
Continuing in #38
