### ISSUE TITLE
No patches can be applied to input file

### ISSUE THREAD

**Issue by AlShaMignon** [xCuri0/ReBarUEFI#39]
**System**

Laptop MSI Prestige 15 A10SC:
 - BIOS Version: E16S3IMS.108
 - GPU: GTX 1650 Max Q /  Mobile
 
**Description**

I can't patch my BIOS file after including the ReBarDxe module. Is there anything else I can do?

![Screenshot 2023-03-15 110652](https://user-images.githubusercontent.com/107493736/225277236-919c91d9-ce17-4774-b556-473e9b002bf0.png)

In UEFIPatch's folder there were two .txt files, "patches.txt" and "patches-misc.txt". I deleted them and only kept the file with the patches the guide explicits: https://github.com/xCuri0/ReBarUEFI/blob/master/UEFIPatch/patches.txt

**Comment by xCuri0** [comment]
It means that there are no patches for your BIOS. Some motherboards (like Chinese Xeons) work without patching and don't have any that apply.

You can still add the ReBarDxe module and 1GB size will probably work
