### ISSUE TITLE
Asus z170-a : unable to find PciBus section in BIOS

### ISSUE THREAD

**Issue by u238** [xCuri0/ReBarUEFI#41]
**System**
 - Motherboard: Asus z170-a
 - BIOS Version: 3802 (https://www.asus.com/us/supportonly/z170a/helpdesk_bios/)
 - GPU: Intel Arc a750 8GB
 - [x] CSM is turned off
 - [ ] 4G decoding is enabled
 - [ ] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [ ] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

Hi,
I saw that some users where able to mod the BIOS but i'm stuck on early stages: I can't even find the correct place where to put the FFS module.
![image](https://user-images.githubusercontent.com/2368573/226722931-95eb2153-f780-41fd-9ebc-13f3c6fbfc2a.png)

Can you please help me finding where to place it?
Can I then flash the BIOS using the flash tool inside the BIOS itself?
Thank you very much in advance, you are making a very great job!!!

**Comment by xCuri0** [comment]
Do a **Header only GUID search** for ```3C1DE39F-D207-408A-AACC-731CFB7F1DD7```. It may not display the name but that will locate the PciBus module

I have updated the wiki also
