### ISSUE TITLE
The guide is very confusing.

### ISSUE THREAD

**Issue by Ckosmick** [xCuri0/ReBarUEFI#56]
**System**
 - Motherboard: Gigabyte G1.Sniper Z170-CF
 - BIOS Version: American Megatrends Inc. F22f, 09-03-2018 (https://www.gigabyte.com/Motherboard/G1Sniper-Z170-rev-10/support#support-dl-bios)
 - GPU: MSI Radeon™ RX 6700 XT GAMING X 12G
 - [x] CSM is turned off
 - [x] 4G decoding is enabled
 - [ ] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [x] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

I don't know what I'm looking at in the screenshots. I'm told to search for a GUID but UEFITool doesn't jump me there so I need to dig around and once I find something that looks right, I must eyeball back and forth between the search result and what I have in the main window to make sure it all matches.

There's screenshots that supposedly show the difference between what a good bios patch and bad bios patch look like but it does not clearly indicate where to look, only to look for a pad file, but the bios has a couple of those already. Am I looking for this pad file at the end of the volume I added ReBarDxe.ffs to? I don't know.

I grabbed the latest NE UEFITool to try and see if it was less confusing / if I did it right and what I find is that I have a message in the NE UefiTool window of my patched rom that says

FfsParser::checkProtectedRanges: AMI v2 protected range [290000h:5C6A00h] hash mismatch, opened image may refuse to boot

Is this borked or not? I can assume it is but the guide does not helpfully explain this. It's frustrating. The whole old engine vs new engine situation confuses things further. I didn't know the answer to "What is 'non-NE?' until i looked at the full releases page and not the specifically linked 0.28 version.

EDIT: Alright I do see what it says to check for now I think I just glossed over it. `You can check for this issue by comparing pad files of the modified volume in UEFITool.`

Maybe this ought to be moved to another paragraph or as part of one of the image captions?

As for the protected range I'm not sure whether to proceed or not still.

![image](https://github.com/xCuri0/ReBarUEFI/assets/88715137/4cc2096c-57bf-4629-ad1e-3bb3d3478be5)

**Comment by Ckosmick** [comment]
Update: I ignored the ami v2 protected range warning and tried flashing patched f22f anyway. Q-flash didn't work even after downgrading to f22c, so I used rufus to make a FreeDOS image on my usb, copied over my patched f22f BIOS and a modded version of efiflash. https://winraid.level1techs.com/t/flashing-gigabyte-while-avoiding-invalid-bios-image/31185

So far so good with 1GB BAR.

**Comment by xCuri0** [comment]
The reason the guide is so confusing and many workarounds is due to UEFITool NE not supporting modification of UEFI images. So you have to use UEFITool 0.28 which has problems handling newer (~2015+) UEFI firmware and non-aligned pad files.

Once UEFITool NE supports modification the guide will become alot easier and no workarounds like MMTool will be needed.

If u have any suggestions for the guide you can mention them

**Comment by Ckosmick** [comment]
That sounds good, appreciate all the work done on this. 
![image](https://github.com/xCuri0/ReBarUEFI/assets/88715137/495179db-889c-446e-888e-6cdeb2b9afc8)

Seems to work set to unlimited with the only issue being the inability to see bios before boot. That said, I have not modified this RX 6700 XT vBIOS in any way. Would connecting to iGPU work in this case? Or would I be looking to try and update GOP too?

**Comment by xCuri0** [comment]
@Ckosmick see https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes)#no-video-output-during-boot-before-os-loads

**Comment by Ckosmick** [comment]
Ahh, will try that, thanks. I currently have above 4G decoding on and csm off.

**Comment by Ckosmick** [comment]
Good news and bad news, the bad news is the fixes in common issues don't work. turning above 4gb decoding off doesn't work.

However, good news, setting "initial display" to iGFX means that when I need to change bios I still can, just with a display connected to iGPU. And I still get above 4G decoding and unlimited resizable bar this way.

**Comment by xCuri0** [comment]
@Ckosmick you supposed turn off the **Above 4G Decoding Patch** option, not **Above 4G Decoding**. it's possible that your bios doesn't have the option

**Comment by Ckosmick** [comment]
I toggled off the "Above 4G decoding" setting in my bios, my system supports that, just not rebar (until now haha)

**Comment by Enterprise12nx01** [comment]
I am also very confused..have Asus Z170I Pro Gaming, i see its suppose to work.
i did all the steps, it named my file (name).CAP.patched
i removed the patched extension and just renamed it, but it wont let me install it as its not a recognized bios or whatever.

Opening the modified bios it says "parseImageFile: Aptio capsule signature may become invalid after image modifications"
i tried to understand the "pad" file thing but i have no idea what im looking or comparing to, if its needed and how i can flash it

**Comment by xCuri0** [comment]
@Enterprise12nx01 

> parseImageFile: Aptio capsule signature may become invalid after image modifications

this is safe to ignore.

ASUS almost always has pad file issue though, you can try mentioning someone in the working motherboards list who has something similar for help

**Comment by Enterprise12nx01** [comment]
> @Enterprise12nx01
> 
> > parseImageFile: Aptio capsule signature may become invalid after image modifications
> 
> this is safe to ignore.
> 
> ASUS almost always has pad file issue though, you can try mentioning someone in the working motherboards list who has something similar for help.
> 
> Once UEFITool NE gets released with editing support I can simplify the guide a lot since we won't need workarounds for issues like this.

@X3Shadowknight would you be willing to help? I have the same motherboard you marked as working! I would really appreciate it

**Comment by Enterprise12nx01** [comment]
@68k-dude @dsanke @necr0n @Nimayer @Aushyro @Phil-Libra
sorry for the tags, i saw some of you have done Z170 boards, i was hoping somebody could help, pretty sure im good up until the pad part of the guide, and also flashing it as it seems ezflash3 will deny it

**Comment by dsanke** [comment]
@Enterprise12nx01 you need a spi programmer(hardware) to flash modified/unofficial bios, this is the most convenient way.
i can provide you modified bios if you are able to flash unofficial bios.

**Comment by Enterprise12nx01** [comment]
> @Enterprise12nx01 you need a spi programmer(hardware) to flash modified/unofficial bios, this is the most convenient way. i can provide you modified bios if you are able to flash unofficial bios.

Ooof no other way? i will just settle without it ig, im not even sure how to do that
