### ISSUE TITLE
Weird CPU support 

### ISSUE THREAD

**Issue by GiulianoB-1** [xCuri0/ReBarUEFI#60]
not a bug but a question. i have a motherboard ROG strix x299-E, a i7-7740x cpu and rtx 3070 FE. My gpu and motherboard support resizable bar tho according to intel, it seems that my cpu isn't supported. However, when I enable resizable bar in my bios, nvidia control panel and GPU-z reports resizable bar as enabled. So is cpu support really is needed or not? and if cpu supported is needed, do i need to use the ReBarUEFI too to fix it?

**Comment by xCuri0** [comment]
Any CPU from ~2010 should be able to support rebar even if it's PCIe 2.0. I'm unsure about earlier stuff because no one has tried it.

**Comment by GiulianoB-1** [comment]
So I dont need to use ReBarUEFI?

**Comment by xCuri0** [comment]
@GiulianoB-1 if you're motherboard has rebar option in BIOS no, because you can use that instead
