### ISSUE TITLE
Asus P8Z68-V-LX DSDT Patch

### ISSUE THREAD

**Issue by Zilog80c** [xCuri0/ReBarUEFI#71]
Hi to all,
 i search to apply DSDT patch to bios Asus P8Z68-V-LX.
When compile with iasl DSDTMod.dsl, i have this error:

DSDTMod.dsl  11512:         Name (_HID, "ABCDEFGH")  // _HID: Hardware ID
Error    6035 -                                 ^ _HID suffix must be all hex digits (GH)

Can i help me.
Very Very thanks a lot.

**Comment by xCuri0** [comment]
It says at bottom of page how to fix this
