### ISSUE TITLE
ReBarState -> original bios resizable bar problem

### ISSUE THREAD

**Issue by xxxviom** [xCuri0/ReBarUEFI#72]
**System**
 - Motherboard: Gigabyte B365M D3H
 - CPU Core i5 9400F
 - BIOS Version: F4
 - GPU: Arc A750 LE
 - [x] CSM is turned off
 - [x] 4G decoding is enabled
 - [x] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

UEFIPatched was applied.  Bar>1Gb - system not starting.
Bar=1Gb - GPU-Z and Arc control shows that rebar not enabled in BIOS.

Then I found a new BIOS version for my mobo with Resizable Bar option (disabled/auto). Successfully upgraded, resizable bar - AUTO. GPU-Z and Arc control still shows that rebar not enabled in bios...

So... Could it be that ReBarState blocking original rebar function in NOT modified BIOS?

**Comment by xCuri0** [comment]
ReBarState does nothin unless you have the ReBarDxe module inserted so no
