### ISSUE TITLE
Enhance `Failed to write ReBarState UEFI variable` error message

### ISSUE THREAD

**Issue by miyconst** [xCuri0/ReBarUEFI#8]
The `Failed to write ReBarState UEFI variable` error message provides zero information about the problem, but according to the [`SetFirmwareEnvironmentVariableExA`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setfirmwareenvironmentvariableexa) docs, it should be possible to get at least something using the [`GetLastError`](https://learn.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-getlasterror) method.

**Comment by xCuri0** [comment]
latest version print's the error from GetLastError. it's in releases
