### ISSUE TITLE
Black Screen Issue When Enabling 4G Decoding on X79G V1.51 Motherboard

### ISSUE THREAD

**Issue by crqzys70rm** [xCuri0/ReBarUEFI#87]
I recently obtained an X79 motherboard coupled with an Intel(R) Xeon(R) CPU E5-2650 v2. Due to a previous mishap occurred when I attempted to perform a task involving a Z97 motherboard. At that time, I encountered difficulties due to a misunderstanding of the instructions provided on a wiki or documentation resource. My misinterpretation of those instructions led to damage to the Z97 motherboard, which has made me seeking assistance. I am approaching this setup with caution to prevent further damage. 

I reached DSDT patching are on wiki and upon following meticulous instructions, I reached a crucial step where I needed to enable 4G decoding. After doing so and restarting the system, I encountered a black screen, rendering my system unresponsive. In an attempt to address the black screen issue, I initiated a hard restart. However, this did not resolve the problem, and I was still unable to proceed. I subsequently tried to reset the CMOS, which did bring back the display but reset all the BIOS settings that needed to be configured. Even with 4G decoding enabled, I still couldn't get a display.

I took the initiative to research and explore possible solutions to my issue. I delved into various resources, including one mentioned in issue #48. However, none of these solutions seemed to provide the resolution I desperately needed. I'm hesitant to continue experimenting with settings as they appear to have little relevance to my specific issue.

At this point, I find myself at a loss, with my system still displaying a black screen after enabling 4G decoding. Despite extensive research and several attempts to resolve the issue, I remain unable to progress. Your assistance in troubleshooting this problem would be greatly appreciated.

![379636919_860131605629538_3090338183156291094_n](https://github.com/xCuri0/ReBarUEFI/assets/145791371/a49837b8-ec78-41b7-883c-68a0fd75c3d6)

**Comment by xCuri0** [comment]
Is CSM off ? CSM off should work on it's own, if it doesn't then there's an issue with your GPU VBIOS which Common Issues in wiki says how to fix

Also the guide says DSDT patching is **NOT** needed on HEDT systems like X79.

Btw you can fix your Z97 board just flash back stock bios.

**Comment by xCuri0** [comment]
These Chinese X79/X99 boards typically have working 4G decoding already, atleast for others with them.

**Comment by Squall-Leonhart** [comment]
> These Chinese X79/X99 boards typically have working 4G decoding already, atleast for others with them.

thats because they tend to not have actual x79/x99 chipsets on them.

**Comment by xCuri0** [comment]
Afaik the chipset doesn't matter for resizable bar. Issue is  that the OEM didn't correctly do 4G decoding

**Comment by xCuri0** [comment]
Closing because this issue is most likely fixed now, see #48
