### ISSUE TITLE
Asus Z170i pro gaming ReBar NotWorking

### ISSUE THREAD

**Issue by ShockTime** [xCuri0/ReBarUEFI#88]
**System**
 - Motherboard: Asus Z170i pro gaming ( CPU Xeon E-2186m)
 - BIOS Version: 3805
 - GPU: sapphire 6700XT
 - [X] CSM is turned off
 - [X] 4G decoding is enabled
 - [X] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [X] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

Describe the issue here. 
I used UEFIPatch. Mod bios with coffemod 0.99 and .ffs file and flash afudos. This hack not working for me. Please help!
[https://disk.yandex.ru/i/w7zcu3hwBwPRMg](url)

**Comment by xCuri0** [comment]
Did you run ReBarState ?

**Comment by ShockTime** [comment]
Yes of course
[https://disk.yandex.ru/i/_7lECdmcSRPmWA](url)

**Comment by xCuri0** [comment]
@ShockTime your rebarstate is set to 256mb. that is why it won't work.

you're supposed to set it to 32 (unlimited) or the size you want (16gb in this case)

**Comment by ShockTime** [comment]
@xCuri0 
Anything more than 256Mb does not allow you to load the system in a normal state.
Error with loading W11. "b1initialize library faild 0xc00000BB" and stop system.

**Comment by xCuri0** [comment]
@ShockTime what size did you try ?

try doing 32, some of these z170 boards don't like 2/4gb bar size.

it should work fine, i've seen some people have POST issues but windows always worked.

**Comment by ShockTime** [comment]
@xCuri0 
8,9,10
All but 8 caused problems and I stopped the experiments. 8 it half-work default.

**Comment by xCuri0** [comment]
@ShockTime use 32

**Comment by ShockTime** [comment]
Goodjob. 
'32-unlimited" worked. But pc speaker do it 1 long 3 short (2 cycle) and load windows normaly. 
Start menu bios "black screen".
![Image](https://downloader.disk.yandex.ru/preview/e0f3b5ebacac7519e90ea53ebc5e085b955c1715616bdefca2574dad0611b7bf/651d44c5/Mka-zHdWnRZo9IOTDJCnz-rH0iviEMQehvxCgBEt76v_MAGYYW1wHzWrcIGcoUFeXPjaENuHB2-rxDu0ms6SwQ%3D%3D?uid=0&filename=2023-10-04_09-08-10.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&owner_uid=0&tknv=v2&size=2048x2048)

**Comment by xCuri0** [comment]
@ShockTime that is normal others report the same

**Comment by ShockTime** [comment]
@xCuri0 
It's worked for me but realtekHD error ^_^

**Comment by xCuri0** [comment]
See #4 same issue

**Comment by Enterprise12nx01** [comment]
I want to do this modification for the same board, what should i do?
first step when searching "4G Decod" i get 2 options from search 

<img width="960" alt="Image" src="https://github.com/user-attachments/assets/26c72770-98f7-45b2-845b-7b7d82399d8a" />
