### ISSUE TITLE
Need help with DSDT patching

### ISSUE THREAD

**Issue by belesspathetic** [xCuri0/ReBarUEFI#94]
**System**
 - Motherboard: asrock z170 pro4 
 - BIOS Version: 7.50
 - GPU: Intel Arc a750
 - [yes] CSM is turned off
 - [yes] 4G decoding is enabled
 - [+-] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [yes] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**
Hello there!
I actually cant use my GPU and think is because of this topic **If you're unable to boot Windows or have non functioning GPU with 4G Decoding on then this modification will be required. Usually this issue is on ASRock boards.**

I need some help with my modded BIOS. The problem is I cant figure out how to patch DSDT raw section. Typically compiler gave me some syntax errors.
Can give more information if someone can help me ^_^
PS. command for enable 4G decod is (setup_var 0x387 0x1) 
Thanks!

**Comment by xCuri0** [comment]
There are fixes for errors at the bottom of the page
