### ISSUE TITLE
Asus Sabertooth Z77 with Tesla P40

### ISSUE THREAD

**Issue by dcarrion87** [xCuri0/ReBarUEFI#95]
**System**
 - Motherboard: Asus Sabertooth Z77
 - BIOS Version: 2104
 - GPU: P40 24GB
 - [ X ] CSM is turned off
 - [ ] 4G decoding is enabled
 - [ ] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [X] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

I have a similar issue to https://github.com/xCuri0/ReBarUEFI/issues/77. 

CSM is disabled, Memory Remapping disabled. I've tried memory remapping enabled and nvidia-smi doesn't work with no device found and dmesg showing IO region errors.

I think I only need to do the DSDT patch?

Currently running with 8GB RAM trying to get a 24GB P40 working on Ubuntu 22.04

I followed the DSDT patching guide https://github.com/xCuri0/ReBarUEFI/wiki/Sandy-and-Ivy-Bridge-32GB-BAR-DSDT-modification but can't even get it to compile at the moment. The error lines don't match up.

Just wondering if someone could point me in the right direction so I can diff the files to see where I'm going wrong. The original output files:

[errors.log.txt](https://github.com/xCuri0/ReBarUEFI/files/13268733/errors.log.txt)

[dsdt.dsl.txt](https://github.com/xCuri0/ReBarUEFI/files/13268734/dsdt.dsl.txt)

[dsdt.dat.txt](https://github.com/xCuri0/ReBarUEFI/files/13268735/dsdt.dat.txt)

**Comment by dcarrion87** [comment]
Nevermind, I am blind. 

Got it working with 16GB RAM. Could not take it to 24GB. Any thoughts?

Here's the modified file:

[dsdt.dsl.txt](https://github.com/xCuri0/ReBarUEFI/files/13269192/dsdt.dsl.txt)

```
# free -m
               total        used        free      shared  buff/cache   available
Mem:           15156         287       14562           1         306       14597
Swap:           4095           0        4095
```

```
# nvidia-smi
Mon Nov  6 15:56:31 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P40                      Off | 00000000:01:00.0 Off |                  Off |
| N/A   50C    P0              51W / 250W |      0MiB / 24576MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by xCuri0** [comment]
@dcarrion87 probably some address space limitation, dmesg should say why.

you're lucky 16GB RAM works because for others only 8GB worked
