### ISSUE TITLE
i can't flash modded uefi file

### ISSUE THREAD

**Issue by leonpano2006** [xCuri0/ReBarUEFI#96]
**System**
 - Motherboard: HPE ML350 Gen9
 - BIOS Version:P92_3.30
 - GPU:RTX A5000 + ilo4 2d (disabled after post)
 - [x] CSM is turned off --> i have no reason to install legecy system at all
 - [x] 4G decoding is enabled --> even i find no option of 4G decoding, but gpuz confirm is enabled
 - [x] UEFIPatch is applied (see [Using UEFIPatch](https://github.com/xCuri0/ReBarUEFI/wiki/Using-UEFIPatch) for more information). On some motherboards [DSDT Patching](https://github.com/xCuri0/ReBarUEFI/wiki/DSDT-Patching) is also needed
 - [x] I have read [Common issues (and fixes)](https://github.com/xCuri0/ReBarUEFI/wiki/Common-issues-(and-fixes))

**Description**

after i modify with ReBarDxe thing and build
then i tried to flash and get this error
![image](https://github.com/xCuri0/ReBarUEFI/assets/58368166/7e5d9ef1-83ca-45b2-a4eb-4e151bebc825)

[P92_3.30_09_21_2023.zip](https://github.com/xCuri0/ReBarUEFI/files/13299338/P92_3.30_09_21_2023.zip)
unmodded uefi and modded uefi inculded

**Comment by xCuri0** [comment]
It probably has a signature check you will need to use another method like hardware flasher

**Comment by leonpano2006** [comment]
> It probably has a signature check you will need to use another method like hardware flasher

And then ilo may complain about UEFI on startup and halt device

**Comment by fthobe** [comment]
@xCuri0 any proven examples of this working with gen 10 proliant servers? I checked everywhere but could find only this issue.
