### ISSUE TITLE
Z77X-UD5H 4G decode does not activate

### ISSUE THREAD

**Issue by fabriguzden** [xCuri0/ReBarUEFI#99]
![image](https://github.com/xCuri0/ReBarUEFI/assets/27593140/ea4eb95e-d3d4-4fab-b909-d6c5d8873d1e)
![image](https://github.com/xCuri0/ReBarUEFI/assets/27593140/53df4677-d0e0-4e89-b558-5cdc1c22ca51)

I just checked to see if 4G Decode was enabled and realized it is not, although GPU-Z shows it is active and the step by step instructions are correct, my specs are
i7 3770
Bios F16K Winraid Mod
Z77X-UD5H
16GB of ram at 1300mhz
Rtx 3060 evga 12gb LHR

I realized that I was making mistakes with the commands when enabling 4G decode but now I have a problem and that is that when loading Windows it hangs on the loading wheel and the board sends me an A0 code that is meant to have started correctly but still hangs during boot of windows 11 23h2
![image](https://github.com/xCuri0/ReBarUEFI/assets/27593140/ec4a2ea4-febf-4797-aed9-9cee6b6fef10)

I have also reinstalled the nvidia driver but the nvidia control panel still tells me that there is no Resizable Bar enabled, however GPU-Z tells me that it is enabled even when I change the size of the Bar less than 1gb in GPU-Z it also changes and If I deactivate Bar it also changes to disabled in GPU-Z, so that confirms that ReBar is correctly implemented, the problem is when activating 4G Decode, when starting the Windows system it freezes

Any suggestions?

**Comment by fabriguzden** [comment]
> ![image](https://user-images.githubusercontent.com/27593140/284712967-ea4eb95e-d3d4-4fab-b909-d6c5d8873d1e.png) ![image](https://user-images.githubusercontent.com/27593140/284713317-53df4677-d0e0-4e89-b558-5cdc1c22ca51.png)
> 
> I just checked to see if 4G Decode was enabled and realized it is not, although GPU-Z shows it is active and the step by step instructions are correct, my specs are i7 3770 Bios F16K Winraid Mod Z77X-UD5H 16GB of ram at 1300mhz Rtx 3060 evga 12gb LHR
> 
> When I try to upload 2GB in BAR my PC does not start, it gives me code 95 which means "Check PCI device requested resources" I also get this "If you get an error about GUID mismatch"
> 
> Any suggestions?

**Comment by fabriguzden** [comment]
I realized that I was making mistakes with the commands when enabling 4G decode but now I have a problem and that is that when loading Windows it hangs on the loading wheel and the board sends me an A0 code that is meant to have started correctly but still hangs during boot

**Comment by xCuri0** [comment]
@fabriguzden 

> I realized that I was making mistakes with the commands when enabling 4G decode but now I have a problem and that is that when loading Windows it hangs on the loading wheel 

did you do DSDT patch and UEFIPatch ?

**Comment by fabriguzden** [comment]
> @fabriguzden
> 
> > I realized that I was making mistakes with the commands when enabling 4G decode but now I have a problem and that is that when loading Windows it hangs on the loading wheel
> 
> did you do DSDT patch and UEFIPatch ?

![image](https://github.com/xCuri0/ReBarUEFI/assets/27593140/9e9d5853-d00a-40f3-94c7-3a3357c75a25)

When I had the problem of the boot in Windows that freezes until that moment I have not applied the DSDT patch, I only applied the UEFI Patch, now a few moments ago the idea of applying the DSDT patch occurred to me because of what it says in your Wiki about DSDT, however I have problems decompiling the DSDT.aml to dsl, iasl shows me 6 uncorrected warnings, it seems decompilation depends on 6 external controls or a declaration in a refs.txt file, but, I leave it as is, I ignore it and continue, after having changed the code to the new one according to the instructions on your wiki and when I am going to compile

> `DSDTMod.dsl   1963:         Device (PCI0)
Warning  3073 -        Multiple types ^  (Device object requires either a _HID or _ADR, but not both)

DSDTMod.dsl   2371:                     CreateDWordField (BUF0, \_SB.PCI0._Y0F._LEN, MSLN)  // _LEN: Length
Warning  3128 -                                    ResourceTag larger than Field ^  (Size mismatch, Tag: 64 bits, Field: 32 bits)

DSDTMod.dsl   3550:                         Acquire (MUT0, 0x0FFF)
Warning  3130 -                                                ^ Result is not used, possible operator timeout will be missed

DSDTMod.dsl   3860:                     Method (DCR4, 2, NotSerialized)
Remark   2146 -     Method Argument is never used ^  (Arg1)

DSDTMod.dsl   4031:                 Method (SIOW, 1, NotSerialized)
Remark   2146 - Method Argument is never used ^  (Arg0)

DSDTMod.dsl   4047:                 Device (PS2K)
Warning  3141 -            Missing dependency ^  (Device has a _PRS, missing a _SRS, required)

DSDTMod.dsl   4113:                 Device (PS2M)
Warning  3141 -            Missing dependency ^  (Device has a _PRS, missing a _SRS, required)

DSDTMod.dsl   7120:                         Name (UPCA, Package (0x04)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01._UPC)

DSDTMod.dsl   7132:                         Name (PLDP, Package (0x01)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01._PLD)

DSDTMod.dsl   7148:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR11._UPC)

DSDTMod.dsl   7160:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR11._PLD)

DSDTMod.dsl   7177:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR12._UPC)

DSDTMod.dsl   7189:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR12._PLD)

DSDTMod.dsl   7206:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR13._UPC)

DSDTMod.dsl   7218:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR13._PLD)

DSDTMod.dsl   7235:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR14._UPC)

DSDTMod.dsl   7247:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR14._PLD)

DSDTMod.dsl   7261:                             If ((Arg0 == ToUUID ("a5fc708f-8775-4ba6-bd0c-ba90a1ec72f8") /* Unknown UUID */))
Remark   2184 -                                                                      Unknown UUID string ^

DSDTMod.dsl   7263:                                 Name (_T_0, Zero)  // _T_x: Emitted by ASL Compiler, x=0-9, A-Z
Remark   2011 -               Use of compiler reserved name ^  (_T_0)

DSDTMod.dsl   7308:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR15._UPC)

DSDTMod.dsl   7320:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR15._PLD)

DSDTMod.dsl   7334:                             If ((Arg0 == ToUUID ("a5fc708f-8775-4ba6-bd0c-ba90a1ec72f8") /* Unknown UUID */))
Remark   2184 -                                                                      Unknown UUID string ^

DSDTMod.dsl   7336:                                 Name (_T_0, Zero)  // _T_x: Emitted by ASL Compiler, x=0-9, A-Z
Remark   2011 -               Use of compiler reserved name ^  (_T_0)

DSDTMod.dsl   7381:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR16._UPC)

DSDTMod.dsl   7393:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR16._PLD)

DSDTMod.dsl   7407:                             If ((Arg0 == ToUUID ("a5fc708f-8775-4ba6-bd0c-ba90a1ec72f8") /* Unknown UUID */))
Remark   2184 -                                                                      Unknown UUID string ^

DSDTMod.dsl   7409:                                 Name (_T_0, Zero)  // _T_x: Emitted by ASL Compiler, x=0-9, A-Z
Remark   2011 -               Use of compiler reserved name ^  (_T_0)

DSDTMod.dsl   7454:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR17._UPC)

DSDTMod.dsl   7466:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR17._PLD)

DSDTMod.dsl   7480:                             If ((Arg0 == ToUUID ("a5fc708f-8775-4ba6-bd0c-ba90a1ec72f8") /* Unknown UUID */))
Remark   2184 -                                                                      Unknown UUID string ^

DSDTMod.dsl   7482:                                 Name (_T_0, Zero)  // _T_x: Emitted by ASL Compiler, x=0-9, A-Z
Remark   2011 -               Use of compiler reserved name ^  (_T_0)

DSDTMod.dsl   7527:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR18._UPC)

DSDTMod.dsl   7539:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC1.HUBN.PR01.PR18._PLD)

DSDTMod.dsl   7599:                         Name (UPCA, Package (0x04)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01._UPC)

DSDTMod.dsl   7611:                         Name (PLDP, Package (0x01)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01._PLD)

DSDTMod.dsl   7627:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01.PR11._UPC)

DSDTMod.dsl   7639:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01.PR11._PLD)

DSDTMod.dsl   7656:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01.PR12._UPC)

DSDTMod.dsl   7668:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01.PR12._PLD)

DSDTMod.dsl   7682:                             If ((Arg0 == ToUUID ("a5fc708f-8775-4ba6-bd0c-ba90a1ec72f8") /* Unknown UUID */))
Remark   2184 -                                                                      Unknown UUID string ^

DSDTMod.dsl   7684:                                 Name (_T_0, Zero)  // _T_x: Emitted by ASL Compiler, x=0-9, A-Z
Remark   2011 -               Use of compiler reserved name ^  (_T_0)

DSDTMod.dsl   7729:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01.PR13._UPC)

DSDTMod.dsl   7741:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01.PR13._PLD)

DSDTMod.dsl   7755:                             If ((Arg0 == ToUUID ("a5fc708f-8775-4ba6-bd0c-ba90a1ec72f8") /* Unknown UUID */))
Remark   2184 -                                                                      Unknown UUID string ^

DSDTMod.dsl   7757:                                 Name (_T_0, Zero)  // _T_x: Emitted by ASL Compiler, x=0-9, A-Z
Remark   2011 -               Use of compiler reserved name ^  (_T_0)

DSDTMod.dsl   7802:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01.PR14._UPC)

DSDTMod.dsl   7814:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01.PR14._PLD)

DSDTMod.dsl   7831:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01.PR15._UPC)

DSDTMod.dsl   7843:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01.PR15._PLD)

DSDTMod.dsl   7860:                             Name (UPCP, Package (0x04)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01.PR16._UPC)

DSDTMod.dsl   7872:                             Name (PLDP, Package (0x01)
Remark   2173 -                                         ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.EHC2.HUBN.PR01.PR16._PLD)

DSDTMod.dsl   7912:                 If ((Arg0 == ToUUID ("7c9512a9-1705-4cb4-af7d-506a2423ab71") /* Unknown UUID */))
Remark   2184 -                                                          Unknown UUID string ^

DSDTMod.dsl   7920:             Method (POSC, 3, Serialized)
Remark   2146 -                           ^ Method Argument is never used (Arg0)

DSDTMod.dsl   8003:                         Name (UPCP, Package (0x04)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.HSP1._UPC)

DSDTMod.dsl   8020:                         Name (PLDP, Package (0x01)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.HSP1._PLD)

DSDTMod.dsl   8043:                         Name (UPCP, Package (0x04)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.HSP2._UPC)

DSDTMod.dsl   8060:                         Name (PLDP, Package (0x01)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.HSP2._PLD)

DSDTMod.dsl   8083:                         Name (UPCP, Package (0x04)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.HSP3._UPC)

DSDTMod.dsl   8095:                         Name (PLDP, Package (0x01)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.HSP3._PLD)

DSDTMod.dsl   8112:                         Name (UPCP, Package (0x04)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.HSP4._UPC)

DSDTMod.dsl   8124:                         Name (PLDP, Package (0x01)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.HSP4._PLD)

DSDTMod.dsl   8141:                         Name (UPCP, Package (0x04)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.SSP1._UPC)

DSDTMod.dsl   8158:                         Name (PLDP, Package (0x01)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.SSP1._PLD)

DSDTMod.dsl   8181:                         Name (UPCP, Package (0x04)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.SSP2._UPC)

DSDTMod.dsl   8198:                         Name (PLDP, Package (0x01)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.SSP2._PLD)

DSDTMod.dsl   8221:                         Name (UPCP, Package (0x04)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.SSP3._UPC)

DSDTMod.dsl   8233:                         Name (PLDP, Package (0x01)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.SSP3._PLD)

DSDTMod.dsl   8250:                         Name (UPCP, Package (0x04)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.SSP4._UPC)

DSDTMod.dsl   8262:                         Name (PLDP, Package (0x01)
Remark   2173 -                                     ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.XHC.RHUB.SSP4._PLD)

DSDTMod.dsl   8523:                 Name (TBUF, Buffer (0x0100){})
Remark   2173 -                             ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.SBUS.SBLR)

DSDTMod.dsl   8840:     Method (UXDV, 1, NotSerialized)
Remark   2120 -                   ^ Control Method should be made Serialized due to creation of named objects within (\UXDV)

DSDTMod.dsl   8843:         Name (_T_0, Zero)  // _T_x: Emitted by ASL Compiler, x=0-9, A-Z
Remark   2011 -                     ^ Use of compiler reserved name (_T_0)

DSDTMod.dsl   8881:     Method (RRIO, 4, NotSerialized)
Remark   2146 -                   ^ Method Argument is never used (Arg3)

DSDTMod.dsl   8881:     Method (RRIO, 4, NotSerialized)
Remark   2120 -                   ^ Control Method should be made Serialized due to creation of named objects within (\RRIO)

DSDTMod.dsl   8883:         Name (_T_0, Zero)  // _T_x: Emitted by ASL Compiler, x=0-9, A-Z
Remark   2011 -                     ^ Use of compiler reserved name (_T_0)

DSDTMod.dsl   9088:     Method (RDMA, 3, NotSerialized)
Remark   2146 -                   ^ Method Argument is never used (Arg0)

DSDTMod.dsl   9088:     Method (RDMA, 3, NotSerialized)
Remark   2146 -                   ^ Method Argument is never used (Arg1)

DSDTMod.dsl   9088:     Method (RDMA, 3, NotSerialized)
Remark   2146 -                   ^ Method Argument is never used (Arg2)

DSDTMod.dsl   9094:         Method (NPTS, 1, NotSerialized)
Remark   2146 -                       ^ Method Argument is never used (Arg0)

DSDTMod.dsl   9098:         Method (NWAK, 1, NotSerialized)
Remark   2146 -                       ^ Method Argument is never used (Arg0)

DSDTMod.dsl   9182:             Method (_DOD, 0, NotSerialized)  // _DOD: Display Output Devices
Remark   2120 -                           ^ Control Method should be made Serialized due to creation of named objects within (\_SB.PCI0.GFX0._DOD)

DSDTMod.dsl   9234:                     Name (TMP1, Package (0x01)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.GFX0._DOD)

DSDTMod.dsl   9244:                     Name (TMP2, Package (0x02)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.GFX0._DOD)

DSDTMod.dsl   9256:                     Name (TMP3, Package (0x03)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.GFX0._DOD)

DSDTMod.dsl   9270:                     Name (TMP4, Package (0x04)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.GFX0._DOD)

DSDTMod.dsl   9286:                     Name (TMP5, Package (0x05)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.GFX0._DOD)

DSDTMod.dsl   9304:                     Name (TMP6, Package (0x06)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.GFX0._DOD)

DSDTMod.dsl   9324:                     Name (TMP7, Package (0x07)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.GFX0._DOD)

DSDTMod.dsl   9346:                     Name (TMP8, Package (0x08)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.GFX0._DOD)

DSDTMod.dsl  10385:                     Sleep (ASLP)
Remark   2159 -                                  ^ Very long Sleep, greater than 1 second

DSDTMod.dsl  10395:                     Sleep (ASLP)
Remark   2159 -                                  ^ Very long Sleep, greater than 1 second

DSDTMod.dsl  10464:                     Sleep (ASLP)
Remark   2159 -                                  ^ Very long Sleep, greater than 1 second

DSDTMod.dsl  10626:         Processor (CPU0, 0x01, 0x00000410, 0x06){}
Warning  3168 -                          ^ Legacy Processor() keyword detected. Use Device() keyword instead.

DSDTMod.dsl  10627:         Processor (CPU1, 0x02, 0x00000410, 0x06){}
Warning  3168 -                          ^ Legacy Processor() keyword detected. Use Device() keyword instead.

DSDTMod.dsl  10628:         Processor (CPU2, 0x03, 0x00000410, 0x06){}
Warning  3168 -                          ^ Legacy Processor() keyword detected. Use Device() keyword instead.

DSDTMod.dsl  10629:         Processor (CPU3, 0x04, 0x00000410, 0x06){}
Warning  3168 -                          ^ Legacy Processor() keyword detected. Use Device() keyword instead.

DSDTMod.dsl  10630:         Processor (CPU4, 0x05, 0x00000410, 0x06){}
Warning  3168 -                          ^ Legacy Processor() keyword detected. Use Device() keyword instead.

DSDTMod.dsl  10631:         Processor (CPU5, 0x06, 0x00000410, 0x06){}
Warning  3168 -                          ^ Legacy Processor() keyword detected. Use Device() keyword instead.

DSDTMod.dsl  10632:         Processor (CPU6, 0x07, 0x00000410, 0x06){}
Warning  3168 -                          ^ Legacy Processor() keyword detected. Use Device() keyword instead.

DSDTMod.dsl  10633:         Processor (CPU7, 0x08, 0x00000410, 0x06){}
Warning  3168 -                          ^ Legacy Processor() keyword detected. Use Device() keyword instead.

DSDTMod.dsl  11033:             If (CondRefOf (_OSI, Local0))
Warning  3144 -       Method Local is set but never used ^  (Local0)

DSDTMod.dsl  12032:             Name (_HID, "pnp0c14")  // _HID: Hardware ID
Error    6136 - Non-hex letters must be upper case ^  (pnp0c14)

DSDTMod.dsl  12040:             Method (WMMX, 3, NotSerialized)
Remark   2146 -                           ^ Method Argument is never used (Arg0)

DSDTMod.dsl  12040:             Method (WMMX, 3, NotSerialized)
Remark   2146 -                           ^ Method Argument is never used (Arg1)

DSDTMod.dsl  12055:         Method (_HID, 0, NotSerialized)  // _HID: Hardware ID
Warning  3115 -                       ^ Not all control paths return a value (\_SB.PCI0.LPCB.TPM._HID)

DSDTMod.dsl  12055:         Method (_HID, 0, NotSerialized)  // _HID: Hardware ID
Warning  3107 -                       ^ Reserved method must return a value (Integer/String required for _HID)

DSDTMod.dsl  12113:         Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
Remark   2120 -                       ^ Control Method should be made Serialized due to creation of named objects within (\_SB.PCI0.LPCB.TPM._DSM)

DSDTMod.dsl  12117:                 Name (_T_0, Zero)  // _T_x: Emitted by ASL Compiler, x=0-9, A-Z
Remark   2011 -                             ^ Use of compiler reserved name (_T_0)

DSDTMod.dsl  12152:                     Name (PPI1, Package (0x02)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.LPCB.TPM._DSM)

DSDTMod.dsl  12173:                     Name (PPI2, Package (0x03)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.LPCB.TPM._DSM)

DSDTMod.dsl  12218:             ElseIf ((Arg0 == ToUUID ("376054ed-cc13-4675-901c-4756d7f2d45d") /* Unknown UUID */))
Remark   2184 -                                                          Unknown UUID string ^

DSDTMod.dsl  12220:                 Name (_T_1, Zero)  // _T_x: Emitted by ASL Compiler, x=0-9, A-Z
Remark   2011 -                             ^ Use of compiler reserved name (_T_1)

DSDTMod.dsl  12320:         Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
Remark   2120 -                       ^ Control Method should be made Serialized due to creation of named objects within (\_SB.PCI0.ITPM._DSM)

DSDTMod.dsl  12324:                 Name (_T_0, Zero)  // _T_x: Emitted by ASL Compiler, x=0-9, A-Z
Remark   2011 -                             ^ Use of compiler reserved name (_T_0)

DSDTMod.dsl  12359:                     Name (PPI1, Package (0x02)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.ITPM._DSM)

DSDTMod.dsl  12380:                     Name (PPI2, Package (0x03)
Remark   2173 -                                 ^ Creation of named objects within a method is highly inefficient, use globals or method local variables instead (\_SB.PCI0.ITPM._DSM)

DSDTMod.dsl  12425:             ElseIf ((Arg0 == ToUUID ("376054ed-cc13-4675-901c-4756d7f2d45d") /* Unknown UUID */))
Remark   2184 -                                                          Unknown UUID string ^

DSDTMod.dsl  12427:                 Name (_T_1, Zero)  // _T_x: Emitted by ASL Compiler, x=0-9, A-Z
Remark   2011 -                             ^ Use of compiler reserved name (_T_1)

DSDTMod.dsl  12572:         Name (_HID, "ABCDEFGH")  // _HID: Hardware ID
Error    6035 -                                 ^ _HID suffix must be all hex digits (GH)

ASL Input:     DSDTMod.dsl -  426835 bytes   5395 keywords      0 source lines

Compilation failed. 2 Errors, 16 Warnings, 101 Remarks
No AML files were generated due to compiler error(s)`

2 errors that do not allow me to compile
![image](https://github.com/xCuri0/ReBarUEFI/assets/27593140/044c8ca0-ad7d-496d-8ef7-f6e8bda6b083)
![image](https://github.com/xCuri0/ReBarUEFI/assets/27593140/2a960bce-698d-4a30-abb2-5013d4086eb2)

**Comment by xCuri0** [comment]
@fabriguzden it says at the bottom of the page how to fix these errors.

once you have modified dsdt and uefipatch resizable bar will work without issues. multiple other users (including me) have it working perfectly on gigabyte lga1155 motherboards

**Comment by fabriguzden** [comment]
I came up with the idea of using AI to correct the code, it has resolved those two errors, let's see if the patch works for me now

**Comment by fabriguzden** [comment]
> @fabriguzden it says at the bottom of the dsdt wiki page how to fix these errors.
> 
> once you have modified dsdt and uefipatch resizable bar will work without issues. multiple other users (including me) have it working perfectly on gigabyte lga1155 motherboards

ooou I hadn't realized xd, I honestly don't know how to program code, that's why it occurred to me to seek help

**Comment by fabriguzden** [comment]
> @fabriguzden it says at the bottom of the dsdt wiki page how to fix these errors.
> 
> once you have modified dsdt and uefipatch resizable bar will work without issues. multiple other users (including me) have it working perfectly on gigabyte lga1155 motherboards

Sorry, but I already applied the two patches, but the problem continues, the Windows loading bar and the Gigabyte logo freeze, it starts loading and then freezes after a while.

**Comment by xCuri0** [comment]
@fabriguzden can you upload your modified bios ?

**Comment by fabriguzden** [comment]
> @fabriguzden¿Puedes subir tu BIOS modificada?

https://github.com/xCuri0/ReBarUEFI/issues/11#issuecomment-1822265060

**Comment by fabriguzden** [comment]
@xCuri0 
[Z77XUD5H ReBar Mod + NVME Support (4G Decode not working).zip](https://github.com/xCuri0/ReBarUEFI/files/13445354/Z77XUD5H.ReBar.Mod.%2B.NVME.Support.4G.Decode.not.working.zip)

**Comment by xCuri0** [comment]
@fabriguzden this bios isn't dsdt patched, that's why it's not working
![image](https://github.com/xCuri0/ReBarUEFI/assets/29529557/661154ba-1e8f-4213-b966-da9f39bb0f58)

**Comment by xCuri0** [comment]
this is what a proper patched dsdt looks like 
![image](https://github.com/xCuri0/ReBarUEFI/assets/29529557/c4b99652-9803-4433-881c-e13269b087ff)

**Comment by fabriguzden** [comment]
@xCuri0 That's strange, if I have applied the dsdt patch, well, way, I'll try it again.
edit: I just enabled the hidden menu with hidden options like Above 4G Decode and I'm wondering if with the hidden option already shown and activated in the BIOS menu it will no longer be necessary to use Grub

**Comment by xCuri0** [comment]
Yes if the menu shows you don't need grub

**Comment by fabriguzden** [comment]
@xCuri0 Thank you very much, ReBar with Above 4G Decode to 16GB ReBar is working correctly, I think I had made the mistake when importing the patch to UEFI Tools, it must be that I added the one that was not Patched and I had not realized

**Comment by Flyw4vy** [comment]
> @xCuri0 Thank you very much, ReBar with Above 4G Decode to 16GB ReBar is working correctly, I think I had made the mistake when importing the patch to UEFI Tools, it must be that I added the one that was not Patched and I had not realized

Upload your latest BIOS please if you have it working now please m8.
